### PR TITLE
[AnalysisQC] Enable EventSelectionQA

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @gconesab @noferini

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel , 
I would merge this, since apparently everything is ok, right?
Chiara

**Comment by benedikt-voelkel** [comment]
Yes, I tested it. Sorry I was not explicit about it. Good to be merged

**Comment by chiarazampolli** [comment]
Wonderful, thanks!

**Pull request merged**
