### PR TITLE
Add QC task for ITS clusters and tracks to MC scripts

### PR DESCRIPTION
**Pull request by iravasen**
Hi @catalinristea and @JianLIUhep this is what discussed via email: add the ITS QC cluster and track to MC productions so that we will be able to check if MC anchoring will be done correctly (cc @chiarazampolli )

I have the following crash when testing the code (run the script `O2DPG_pp_minbias.sh`) on lxplus with the PDPSuite of 25/04 but it does not seem to be related to this code modification:
```
#0  0x00007ff66e822659 in waitpid () from /lib64/libc.so.6
#1  0x00007ff66e79ff62 in do_system () from /lib64/libc.so.6
#2  0x00007ff66e7a0311 in system () from /lib64/libc.so.6
#3  0x00007ff66f573f9c in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x1f79fd0) at /jenkins/workspace/DailyBuilds/AdHocO2Physics/daily-tags.pYGZGfKgjt/SOURCES/ROOT/v6-28-02/v6-28-02/core/unix/src/TUnixSystem.cxx:2104
#4  TUnixSystem::StackTrace (this=0x1f79fd0) at /jenkins/workspace/DailyBuilds/AdHocO2Physics/daily-tags.pYGZGfKgjt/SOURCES/ROOT/v6-28-02/v6-28-02/core/unix/src/TUnixSystem.cxx:2395
#5  0x00007ff676b3a6cb in FairLogger::LogFatalMessage () at /jenkins/workspace/DailyBuilds/AdHocO2Physics/daily-tags.pYGZGfKgjt/SOURCES/FairRoot/v18.4.9/v18.4.9/fairtools/FairLogger.cxx:195
#6  0x00007ff670b4d386 in std::function<void ()>::operator()() const (this=0x7ff670b6bb40 <fair::Logger::fFatalCallback>) at /jenkins/workspace/build-any-ib/sw/20156477/1/slc7_x86-64/GCC-Toolchain/v12.2.0-alice1-5/include/c++/12.2.0/bits/std_function.h:587
#7  fair::Logger::~Logger (this=0x7ffda53c4b10, __in_chrg=<optimized out>) at /jenkins/workspace/build-any-ib/sw/20156477/1/SOURCES/FairLogger/v1.11.1/v1.11.1/logger/Logger.cxx:276
#8  0x00007ff676d790e5 in o2::ccdb::CcdbApi::initTGrid (this=0x219f0f0) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/slc7_x86-64/FairLogger/v1.11.1-13/include/fairlogger/Logger.h:310
#9  0x00007ff676d80af7 in o2::ccdb::CcdbApi::loadFileToMemory (this=0x219f0f0, dest=..., path=..., localHeaders=0x0) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/CCDB/src/CcdbApi.cxx:1666
#10 0x00007ff676d81c19 in o2::ccdb::CcdbApi::navigateURLsAndLoadFileToMemory (this=0x219f0f0, dest=..., curl_handle=0x49d70b0, url=..., headers=0x7ffda53c6b30) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/CCDB/src/CcdbApi.cxx:1631
#11 0x00007ff676d8204b in o2::ccdb::CcdbApi::loadFileToMemory (this=0x219f0f0, dest=..., path=..., metadata=..., timestamp=1546730800000, headers=0x7ffda53c6b30, etag=..., createdNotAfter=..., createdNotBefore=..., considerSnapshot=false) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/CCDB/src/CcdbApi.cxx:1506
#12 0x00007ff676d83714 in o2::ccdb::CcdbApi::retrieveBlob (this=0x219f0f0, path=..., targetdir=..., metadata=..., timestamp=timestamp
entry=1546730800000, preservePath=preservePath
entry=true, localFileName=..., createdNotAfter=..., createdNotBefore=...) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/CCDB/src/CcdbApi.cxx:703
#13 0x0000000000414c9a in anchor_GRPs (opts=..., paths=...) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/slc7_x86-64/GCC-Toolchain/v12.2.0-alice1-5/include/c++/12.2.0/bits/basic_string.tcc:238
#14 0x00000000004157cd in create_MeanVertexObject (opts=...) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/DataFormats/Parameters/src/GRPTool.cxx:240
#15 0x0000000000415a4a in create_GRPs (opts=...) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/DataFormats/Parameters/src/GRPTool.cxx:294
#16 0x0000000000411344 in main (argc=15, argv=0x7ffda53c9e08) at /jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.4h7eWPnKNm/SOURCES/O2/nightly-20230425/rc/nightly-20230425/DataFormats/Parameters/src/GRPTool.cxx:635
~                  
```

### CODE REVIEW

**Comment by JianLIUhep** [comment]
Hi @iravasen, thanks for preparing the PR. I see you are now using the json file "its-clusters-tracks-qc.json" with 100% sampling fraction. Could you please change the data sampling policy to `direct` to reduce the overhead as we did in other json files? Thank you.

**Comment by iravasen** [comment]
@JianLIUhep it's done. thanks.

**Comment by JianLIUhep** [comment]
Hi @iravasen, coming to the problem, to me it seems that it's related to permission for uploading or creating local cache for ccdb. It works with local builds on my local machine.

**Comment by JianLIUhep** [comment]
Hi @chiarazampolli, this PR is tested successfully. Could you have a look and approve it then? Thank you.

**Comment by benedikt-voelkel** [comment]
I see a problem in the CI:
```bash
5-[ERROR] error parsing options of /sw/slc7_x86-64/O2/nightly-20230503-local4/bin/o2-ft0-reco-workflow: unrecognised option '--disable-time-offset-calib'
6:TASK-EXIT-CODE: 1
```
Has that been investigated?
If you think it is fine, could you push another commit to trigger the CI again @iravasen ?
Thanks a lot!

**Comment by chiarazampolli** [comment]
> I see a problem in the CI:
> 
> ```shell
> 5-[ERROR] error parsing options of /sw/slc7_x86-64/O2/nightly-20230503-local4/bin/o2-ft0-reco-workflow: unrecognised option '--disable-time-offset-calib'
> 6:TASK-EXIT-CODE: 1
> ```
> 
> Has that been investigated? If you think it is fine, could you push another commit to trigger the CI again @iravasen ? Thanks a lot!

It seems that the CI runs against an old O2: this option was introduced here:
https://github.com/AliceO2Group/AliceO2/pull/11288

**Comment by iravasen** [comment]
Hi @chiarazampolli @benedikt-voelkel, sorry I missed your comments! Can we merge this PR? The ERROR you see is related to FT0.

**Comment by iravasen** [comment]
Hi again, sorry I just noted that the two tasks, tracks and MC, had the same name `Tracks` in the json. I just changed the MC json: `Tracks` -> `TrackMc`. In this way we avoid conflicts when pushing objects to CCDB since there is at least 1 MO having the same name in the two QC tasks. 

Sorry for that. Now all should be (really) good for me.

**Comment by iravasen** [comment]
HI @chiarazampolli, for me now this can be merged

**Review by benedikt-voelkel — APPROVED** [review]
Fine with me @chiarazampolli @sawenzel

**Pull request merged**
