### PR TITLE
New grpGeomRequest for ITS and MFT jsons

### PR DESCRIPTION
**Pull request by iravasen**
This follows https://github.com/AliceO2Group/QualityControl/pull/2164 
and has to go together with it! 

Before merge wait approval from MFT colleagues.

### CODE REVIEW

**Review by shahor02 — APPROVED** [review]
Thanks @iravasen 
Looks fine to me but better MFT experts also check. I've just noticed, that in opposite to the original QualityControl/Modules/MFT/mft-tracks.json the O2DPG/Data/production/qc-async/mft.json was not requesting the GRPGeom block for the MFTTracks task. This means that the call https://github.com/AliceO2Group/QualityControl/blob/55da459a99b14b920255998b1c40148dce48603f/Modules/MFT/src/QcMFTTrackTask.cxx#L211 was returning default 128 orbits / TF

**Comment by chiarazampolli** [comment]
Hello @iravasen , 
Did you ping the MFT expert? I guess it is Maurice, but I cannot find his github account.

Chiara

**Comment by mcoquet642** [comment]
Hi, after discussing with the MFT QC team these changes are ok from our side. Do you also plan to modify the config files in consul or should we do it ourselves once we have the new FLPSuite ?

**Comment by shahor02** [comment]
Thanks @iravasen , @mcoquet642 !
Yes, eventually also the consul should be modified but only once the new QC is bumped and deployed at P2.
Also, this PR fails since it is built against QualityControl/v1.135.1-local2, I guess we should have it on hold until the QC is bumped (pending to @Barthelemy )

**Comment by iravasen** [comment]
Hi @Barthelemy @shahor02, I guess now this PR can be merged?

**Comment by shahor02** [comment]
Yes! Once the new QC is deployed at P2, one can change also jsons on consul.

**Comment by chiarazampolli** [comment]
Hello @iravasen , 

I guess I can merge now. And I also think that this is needed in view of the memory reduction for QC, right?

Chiara

**Comment by iravasen** [comment]
Yes thanks! Sorry

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Now there are conflicts...

**Pull request merged**
