### PR TITLE
MFT: new configuration check for async qc

### PR DESCRIPTION
**Pull request by Edingrast**
* New MFT configuration check. New code already merged to QC (https://github.com/AliceO2Group/QualityControl/pull/2357).

* This is a changed configuration for async qc for proper timestamp retrieval.

### CODE REVIEW

**Comment by Edingrast** [comment]
Hi @chiarazampolli, I have added new check for async qc for MFT, could you please push it to checks? It is my first PR to this repository, so they are not automatic yet.

**Review by chiarazampolli — APPROVED** [review]
Seems ok to me, @JianLIUhep

**Comment by chiarazampolli** [comment]
Hello @ktf , 

What is the wf that needs special approval? 
 
Screenshot 2024-06-28 at 15 09 05

I will approve it, but first I would like to know what this is about, it is something new... 

Cheers,
Chiara

**Comment by JianLIUhep** [comment]
The code is good to me as well.

**Comment by Edingrast** [comment]
Hi @chiarazampolli, @JianLIUhep, the PR didn't merge due to errors in the checks, however I don't think they are related to my code. Can you please take a look at it and, if all is alright, merge it?

**Comment by chiarazampolli** [comment]
Hello @Edingrast , 

Yes, the errors are unrelated. I am pinging again @ktf , and adding @singiamtel since I don't understand the message in the PR about which I asked here: https://github.com/AliceO2Group/O2DPG/pull/1679#issuecomment-2196873299
I hope they can comment. Then I will merge.

Chiara

**Comment by singiamtel** [comment]
Hi @chiarazampolli ,

> What is the wf that needs special approval?

I believe our workflows need approval if they're not opened by an org member (https://github.com/orgs/AliceO2Group/people) or otherwise trusted member.

Full list of requirements here: https://github.com/alisw/ali-bot/blob/master/list-branch-pr#L146

Cheers,
Sergio

**Comment by chiarazampolli** [comment]
Thanks @singiamtel ! Is it ok then to have this PR? @Edingrast , why are you not part of the ALICE organization?

Chiara

**Comment by Edingrast** [comment]
Hi @chiarazampolli,
I am not sure what you mean by "not being part of the ALICE organization". I am working on ALICE and also on MFT, so I am part of collaboration. I am not listed in the list of org people. The workflow approval is usual when there is a PR from someone new. So far I have made PR in O2Physics and QC (first time there was special approval needed for the first time), after the first PR I was already a trusted member, since I had previous PR.

**Comment by chiarazampolli** [comment]
Hello @singiamtel , 
I am not so expert with the rules in github, I thought maybe you needed to be part of some egroup. 
Anyway, now I approved. Since the remaining tests (blocked by this approval) ran fine, I am merging.

Chiara

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
