### PR TITLE
Fix for ZDC_BC_SHIFT and extra setting for MeanVtx calib (no sec vtx)

### PR DESCRIPTION
**Pull request by chiarazampolli**
@catalinristea , @shahor02

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli 
The failed CI is something @TimoWilken and I wanted to test. It shouldn't have been triggered for this PR in any case

**Comment by chiarazampolli** [comment]
Yes, this PR is not checked in any CI (it is for async reco). 
I will wait to merge till @catalinristea confirms that it worked fine.

**Comment by catalinristea** [comment]
Ciao @chiarazampolli,

Indeed, now the missing runs from 22s could also be processed.
Please note we used the different way of disabling secondary vertexing, though here this is more straightforward.
This PR can be merged safely.

Thanks!

Yours, Catalin.

**Comment by chiarazampolli** [comment]
Thanks for the feedback, @catalinristea !
Merging.

**Pull request merged**
