### PR TITLE
[EMCAL-755, EMCAL-756] Adding EMCAL QC for MC and async reconstruction

### PR DESCRIPTION
**Pull request by mfasDa**
- EMCAL-755: QC workflow for MC
- EMCAL-756: QC workflow for async reconstruction

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ok with me! If nobody has further comments, I will merge by tonight, to have it for the next MC cycle. 
@mfasDa , to be sure, you tested it with the simulation chain, right?

**Comment by mfasDa** [comment]
Currently running, therefore adding WIP label until tests are done

**Review by knopers8 — APPROVED** [review]
It looks correct now, but please do confirm with a test.

**Comment by mfasDa** [comment]
I have tried with the scripts from the current min. bias production LHC21k6, now the emccells.root is there but EMCAL is still excluded from filling the AODs:

```
input sources ITS,MFT,MCH,TPC,ITS-TPC,MFT-MCH,ITS-TPC-TOF,TPC-TOF,FT0,FV0,FDD,CTP,TPC-TRD,ITS-TPC-TRD
```

EMC should be added in order to have the EMC tables filled. 

Using MC/run/examples/O2DPG_pp_minbias_multiple_tf_qc.sh I checked that the EMC QC is running and the output histograms are produced. The following file should be added to the files to be stored: emcDigitsQC.root

**Comment by chiarazampolli** [comment]
Hi @mfasDa ,

Do you mean to change this line:

https://github.com/AliceO2Group/O2DPG/blob/965c5976381fce92da90c77f181f12e64712c591/MC/bin/o2dpg_sim_workflow.py#L853

adding `EMC`? Have you tried it?
I will tell Catalin to include the EMCAL file. 

Cheers,

Chiara

**Comment by knopers8** [comment]
@mfasDa I had a random look at a dozen of the histograms in `qc_mc/EMC/MO/DigitsTask/`. Just to make sure, is it expected that the vast majority is empty? (a few of them have 3 entries, which seems correct)

**Comment by mfasDa** [comment]
@knopers8 `CAL` (Histrograms for the calibration trigger) should be empty, because calibration events are not simulated, however the `PHYS` histograms should be filled. Looking at the output I see that cells are produced however the trigger bit is not set, which will confuse the QC as the trigger class is unknown. Needs to be added in the digitizer.

**Comment by mfasDa** [comment]
Link to fix for Physics Trigger in simulation: https://github.com/AliceO2Group/AliceO2/pull/8089

**Comment by mfasDa** [comment]
After setting the trigger type to PhT in the simulated trigger record the DigitsQC histograms are filled now. I have removed the WIP label in order to have the PR merged. Unfortunately up to now I was not able to test the AOD filling as the workflow crashed in earlier stages.

**Comment by davidrohr** [comment]
The O2 PR was merged, can I merge this now then?

**Comment by chiarazampolli** [comment]
Yes, please (I will do it, since I also can - one iteration less).

**Pull request merged**
