### PR TITLE
[PbPb-async-MC-RelVal][O2-4445]: Remove obsolete cuts for ITS iterations

### PR DESCRIPTION
**Pull request by mconcas**
These selections are obsoleted, and the behaviour has been changed in https://github.com/AliceO2Group/AliceO2/pull/12256
See https://github.com/AliceO2Group/O2DPG/pull/1336 proposing the same change for data.

@mpuccio

### CODE REVIEW

**Review by mpuccio — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @mconcas , @sawenzel , 

For me it is fine, but I would first prefer to understand my doubt here: https://github.com/AliceO2Group/O2DPG/pull/1354#issuecomment-1833541903

Thanks,
Chiara

**Comment by sawenzel** [comment]
@chiarazampolli : I don't fully understand your question. Configs are for sure taken from async ... but if async is missing they are taken from the default config.

**Comment by sawenzel** [comment]
@mconcas : Does this fix https://alice.its.cern.ch/jira/browse/O2-4445 ?

**Comment by mconcas** [comment]
> @mconcas : Does this fix https://alice.its.cern.ch/jira/browse/O2-4445 ?

yes

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
