### PR TITLE
Validate analysis output

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
./o2dpg_analysis_test_config.py validate-output

* check if expected outputs are there for given analyses --> by default check all enabled analyses

* for more options see --help

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@catalinristea What do you think?

E.g.
```bash
${O2DPG_ROOT}/MC/analysis_testing/o2dpg_analysis_test_config.py validate-output -d Analysis
```

would check if all expected outputs are there.

**Comment by catalinristea** [comment]
Hi Benedikt, all

PR is now complete - I have tested it and found it very useful for the validation of AnalysisQC stage.
@chiarazampolli, @sawenzel, @gconesab,  

please merge it, such that we can resume this stage in production.

Thanks a lot!

Yours, Catalin.

**Comment by benedikt-voelkel** [comment]
@chiarazampolli I think you can merge if you have the power. The FST will be skipped in any case. At the moment, it seems that something in the machinery is stuck though so it doesn't even recognise that it should be skipped.
Pinging also @TimoWilken

**Comment by chiarazampolli** [comment]
Done!

**Pull request merged**
