### PR TITLE
LHC22c, d, e appear as JUN

### PR DESCRIPTION
**Pull request by chiarazampolli**
@noferini , @catalinristea

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@mfasDa , @bazinski , @martenole , I believe that 22cde (which are defined as JUN...) were not correct before. Can you please check this change? We need to merge it ASAP for apass4 of these periods.

Thanks,

Chiara

**Comment by mfasDa** [comment]
Indeed I see no readout trigger in LHC22d which means the CTP emulation was not on.

I hope there won't be any future sample with the name "JUN" ...

**Review by martenole — APPROVED** [review]
Sure, if LHCcde appear as JUN this is certainly correct

**Comment by chiarazampolli** [comment]
Thanks for the feedback, merged.

**Pull request merged**
