### PR TITLE
ITS track and cluster sampling fraction from 30 to 100%

### PR DESCRIPTION
**Pull request by iravasen**
cc @chiarazampolli

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hi @iravasen , 
This is not a change in the fraction of accepted tracks, but on the max number of tracks, right?
Chiara

**Comment by iravasen** [comment]
Hi @chiarazampolli, 

- the change of the parameter `fraction` in the json means that 100% of the TFs will be processed by QC 
- the change to `NtracksMAX` produces the change of the x axis of the histogram containing the number of tracks per ROF. This now goes up to 5000 (maybe too high but there is no problem).

**Comment by chiarazampolli** [comment]
Ciao @iravasen , 

Thanks, I was clicking the wrong link from the mail, it brought me to one of the two commits only that is why I was confused. 
Approving and merging.

Chiara

**Review by chiarazampolli — APPROVED** [review]

**Comment by iravasen** [comment]
no problem, thanks!

**Pull request merged**
