### PR TITLE
Script for producing overlay plots

### PR DESCRIPTION
**Pull request by DanielSamitz**
Some things still to fix:

- TH2
- use again TRatioPlot if somehow possible
- checks if all files/objects exist
- maximal number of histograms per plot
- return values in python script

Should work also with TTree, but not tested yet

### CODE REVIEW

**Comment by sawenzel** [comment]
@benedikt-voelkel : Could you please review?

**Review by benedikt-voelkel — APPROVED** [review]
Looks good to me.
As @DanielSamitz indicated, there are still a few small things to do but they are mostly minor. Most important, they do not corrupt RelVal in any way.

**Comment by DanielSamitz** [comment]
The only thing that affects RelVal is that the TH1 ratio plots are now not produced with TRatioPlot, but are "handmade". Should in principle be the same, I will do further testing to make sure that the differences are just in the aesthetics of the plots

**Comment by benedikt-voelkel** [comment]
Yes, sure. But that is fine and I think we could even leave it that way in the future.

**Pull request merged**
