### PR TITLE
add X3872 and Psi2S to Jpsi pi pi

### PR DESCRIPTION
**Pull request by ffionda**

### CODE REVIEW

**Review by crisjahnke — APPROVED** [review]

**Comment by jackal1-66** [comment]
Restarted after fix merged in ali-bot https://github.com/alisw/ali-bot/pull/1423

**Comment by jackal1-66** [comment]
@ffionda the build/O2DPG/sim/o2 failure is real now. Could you please check why the test of  `/O2DPG/MC/config/PWGDQ/ini/Generator_InjectedPromptX3782Midy_TriggerGap.ini` is failing? Do you have a similar behaviour locally (or on lxplus)?

**Comment by ffionda** [comment]
Ciao @jackal1-66, thanks for checking. I think the problem is that the tag R02-02-00-alice2 is needed for EvtGen 
https://github.com/alisw/EVTGEN  (as the PR https://github.com/alisw/EVTGEN/commit/a979196e5de4be631b404ecd48963ac062d18bfd is needed for the generator in this PR).  I installed this EvtGen version locally and it works for me, however I see that on lxplus  only R02-02-00-alice1-XX versions are available, so the simulation of the X3782 doesn't work. Would it be possible to make R02-02-00-alice2 EvtGen version available on grid / lxplus for simulations ? Thank you

**Comment by ffionda** [comment]
Thanks @jackal1-66 for merging the PR. We would need to include it in the production software for anchored pp simulations (I tried the option here https://its.cern.ch/jira/browse/O2-5366 but it seems it doesn't work in this case since if I understood correctly it's really a new generator which is introduced and not just a different configuration of an existing generator). 
So, we would need then to add the following labels: 
+async-2023-pp-apass4
+async-2024-pp-apass1
+async-2022-pp-apass7
Thank you.

**Comment by sawenzel** [comment]
@ffionda @jackal1-66 : In principle this approach should work. It doesn't matter if something is updated or not as long as we use the new variable O2DPG_MC_CONFIG_ROOT (and the relevant commit for this change is itself backported).

@jackal1-66 : Could you do a test with some anchored MC job and see what's missing? I suspect that we also need the alidist change https://github.com/alisw/alidist/pull/5681 to be part of older software tags. @alcaliva @chiarazampolli

**Comment by ffionda** [comment]
Ciao @sawenzel, ok thanks a lot! I don't know if this could help, but I had a deeper look (and make this grid test here https://alimonitor.cern.ch/jobs/jdl.jsp?pid=3212370991), and I think one of the issues is that we would need to make the change O2DPG_ROOT -> O2DPG_MC_CONFIG_ROOT also in other places inside the DQ folder, 
in particular here https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGDQ/external/generator/GeneratorPromptCharmonia.C (for this specific generator)

However, there is probably another thing which I'm not sure whether it could be a problem. For this production, we would need to have Evtgen R02-02-00-alice2 (while the version pointed by existing pp production software from O2sim package, e.g. pp2022 apass7 VO_ALICE@O2PDPSuite::async-async-v1-01-02a-slc9-alidist-async-v1-01-02-1, is R02-02-00-alice1-XX). So, I don't know if this would also be fixed. Hope this helps, thanks a lot!

**Comment by jackal1-66** [comment]
Ciao @ffionda, I just opened https://github.com/AliceO2Group/O2DPG/pull/1817 to fix the wrong environment variables inside the scripts. It was my bad, I committed the .ini configurations change before without actually changing the macros.

**Comment by ffionda** [comment]
Thanks @jackal1-66, this PR (https://github.com/AliceO2Group/O2DPG/pull/1817) actually helps to pick up the correct decay tables. However, I ran some grid tests (anchoring to pp apass7), and while everything works fine for psi2s -> jpsi pi pi (see output here https://alimonitor.cern.ch/catalogue/#/alice/cern.ch/user/f/ffionda/anchorMC_PSI2_test2/output/526641), for the X3782 it doesn't work (see test on aliensh here /alice/cern.ch/user/f/ffionda/anchorMC_X3782_test2/) because of the EvtGen issue I mentioned above (i.e. EvtGen R02-02-00-alice1-XX is picked up by the production software, while we would need  R02-02-00-alice2. 
So, do you (@sawenzel, @jackal1-66 ) think it is possible to make the porting of this EvtGen PR https://github.com/alisw/EVTGEN/pull/3 in the production software ? Or do you have any other suggestion on how we could solve this ?
Thanks a lot.

**Comment by jackal1-66** [comment]
Hello @ffionda, thanks for the tests. The modifications to EvtGen are not extreme, so I don't think it would be a problem porting them in production @chiarazampolli @alcaliva. @ffionda did you try changing the O2DPG_MC_CONFIG_ROOT variable or did you simply run the tests on the 30 of Novermber?

**Comment by ffionda** [comment]
Ciao @jackal1-66, thanks for the answer. Yes, I confirm that I changed the O2DPG_MC_CONFIG_ROOT variable setting it to the version of 30 November (here you can see the corresponding script https://alimonitor.cern.ch/users/download.jsp?view=true&path=/alice/cern.ch/user/f/ffionda/anchorMC_X3782_test2/runme.sh I used in the test to set it), but it doesn't help (as I guess EvtGen is picked up from O2sim package). Thanks a lot.

**Comment by chiarazampolli** [comment]
> Hello @ffionda, thanks for the tests. The modifications to EvtGen are not extreme, so I don't think it would be a problem porting them in production @chiarazampolli @alcaliva. @ffionda did you try changing the O2DPG_MC_CONFIG_ROOT variable or did you simply run the tests on the 30 of Novermber?

Hello @jackal1-66 , 
Do I understand that you'd like to update alidist? For which build? What is the target production for this PR? Do I understand from @ffionda that she needs:
+async-2023-pp-apass4
+async-2024-pp-apass1
+async-2022-pp-apass7
The right way is that she tries to compile the sw related to those labels with updated EvGen (so updated alidist, that might need to be patched since taking master might not work). If it works, we can do the same centrally.

Can you follow this with @alcaliva  and @catalinristea ? I am away these days, with very slow reaction time...

Chiara

**Comment by ffionda** [comment]
Ciao @chiarazampolli 
thanks a lot for your answer and for the details. Yes, I confirm that we would need the anchoring to pp 2022 / 23 / 24 (i.e.  +async-2023-pp-apass4, +async-2024-pp-apass1, +async-2022-pp-apass7). 
Ok, so if I understood correctly, I have to try to compile the software production version (with the EvtGen fix in alidist) locally and see if it works (I'm not 100% sure if I should do it for all the three software production versions for the different pp years, maybe I'll start from the one of 2022...). I can try in the next days (if needed I will probably contact Alberto and Catalin to ask for more details).
Thanks a lot for your help,
Cheers,

Fiorella

**Comment by ffionda** [comment]
Ciao @chiarazampolli, @alcaliva, @catalinristea, @jackal1-66 
I managed to compile locally the O2Physics@async-v1-01 / O2@async-v1-01 packages, as well as EvtGen for which I considered the updated alidist/evtgen.sh  (where the correct EvtGen version R02-02-00-alice2 is picked up). The compilation of O2 / O2Physics and EvtGen (as well as the loading of the corresponding packages) worked well for me (for completeness I'm attaching the screenshot). Do you think it's possible to try it centrally ? Just let me know if you need something else from our side.
Thanks, Fiorella
screenshot

**Pull request merged**
