### PR TITLE
TOF: adapt to change in CCDB fetcher

### PR DESCRIPTION
**Pull request by ercolessi**
Change required after the merge of this PR: https://github.com/AliceO2Group/QualityControl/pull/2261
Following also https://its.cern.ch/jira/browse/QC-1166

Could you confirm if this change enough @ktf @chiarazampolli ?

cc: @noferini @njacazio

### CODE REVIEW

**Comment by noferini** [comment]
We probably need to update 
MC/config/QC/json/tofdigits.json
as well.
I will run a test as soon as the today tag is available

**Comment by ercolessi** [comment]
I disabled the call to calibration objects in the jsons since in production we saw this new call produces crashes to be understood.

@noferini @ktf @chiarazampolli

**Review by noferini — APPROVED** [review]
It looks fine. Thanks

**Comment by chiarazampolli** [comment]
Hello @ercolessi , 
What do you mean that in production it crashes?
Here what I am successfully running locally for async reco:
```

zampolli@pcalicecz5:~/SOFT/alibuild/ali-o2-dev1/O2DPG$ git diff
diff --git a/DATA/production/qc-async/tof.json b/DATA/production/qc-async/tof.json
index f8a259e1..5ffaf3d3 100644
--- a/DATA/production/qc-async/tof.json
+++ b/DATA/production/qc-async/tof.json
@@ -33,7 +33,7 @@
         "maxNumberCycles": "-1",
         "dataSource": {
           "type": "direct",
-          "query": "tofdigits:TOF/DIGITS/0;readoutwin:TOF/READOUTWINDOW/0;patterns:TOF/PATTERNS;diafreq:TOF/DIAFREQ/0",
+          "query": "tofdigits:TOF/DIGITS/0;readoutwin:TOF/READOUTWINDOW/0;patterns:TOF/PATTERNS;diafreq:TOF/DIAFREQ/0;channelCalib:TOF/CHCALIB/0?lifetime=condition&ccdb-path=TOF/Calib/ChannelCalib;lhcPhase:TOF/LHCP/0?lifetime=condition&ccdb-path=TOF/Calib/LHCphase",
           "query_comment" : "100% sampling"
         },
         "taskParameters": {
```

**Comment by noferini** [comment]
> Hello @ercolessi , What do you mean that in production it crashes? Here what I am successfully running locally for async reco:
> 
> ```
> 
> zampolli@pcalicecz5:~/SOFT/alibuild/ali-o2-dev1/O2DPG$ git diff
> diff --git a/DATA/production/qc-async/tof.json b/DATA/production/qc-async/tof.json
> index f8a259e1..5ffaf3d3 100644
> --- a/DATA/production/qc-async/tof.json
> +++ b/DATA/production/qc-async/tof.json
> @@ -33,7 +33,7 @@
>          "maxNumberCycles": "-1",
>          "dataSource": {
>            "type": "direct",
> -          "query": "tofdigits:TOF/DIGITS/0;readoutwin:TOF/READOUTWINDOW/0;patterns:TOF/PATTERNS;diafreq:TOF/DIAFREQ/0",
> +          "query": "tofdigits:TOF/DIGITS/0;readoutwin:TOF/READOUTWINDOW/0;patterns:TOF/PATTERNS;diafreq:TOF/DIAFREQ/0;channelCalib:TOF/CHCALIB/0?lifetime=condition&ccdb-path=TOF/Calib/ChannelCalib;lhcPhase:TOF/LHCP/0?lifetime=condition&ccdb-path=TOF/Calib/LHCphase",
>            "query_comment" : "100% sampling"
>          },
>          "taskParameters": {
> ```

It crashed at P2 in data acquisition

**Comment by chiarazampolli** [comment]
Async reco does not crash, I would leave the json for async with the flag "true", if that is correct.
Chiara

**Comment by noferini** [comment]
> Async reco does not crash, I would leave the json for async with the flag "true", if that is correct. Chiara

It is a risk. Up to you

**Comment by chiarazampolli** [comment]
But what should be the flag? true or false? Isn't it wrong to have the wrong value, just because it works?

**Comment by noferini** [comment]
> But what should be the flag? true or false? Isn't it wrong to have the wrong value, just because it works?

From our point of view they are both valid. We don't strictly need calibrations for QC

**Comment by chiarazampolli** [comment]
Ok, then let's make everything consistent, even if I think one should investigate why it fails - for me it is not normal. Don't you have a valid entry maybe? A default one for QC, or one from a previous run?

**Comment by ktf** [comment]
Maybe I missed it, could we have the stacktrace of the crash?

**Comment by chiarazampolli** [comment]
Hello @noferini , @ercolessi , 
I can merge this, but I think we should understand what is making the online reco fail. What do you think?
Chiara

**Comment by noferini** [comment]
> Hello @noferini , @ercolessi , I can merge this, but I think we should understand what is making the online reco fail. What do you think? Chiara

As discussed also on Monday we are following up this with @ktf

**Comment by chiarazampolli** [comment]
Hello @ercolessi , @noferini , 
Should I merge?
Chiara

**Comment by noferini** [comment]
H @chiarazampolli , we can merge it.
Francesco

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
