### PR TITLE
Modification of its.json in qc_async

### PR DESCRIPTION
**Pull request by iravasen**
Modification of its.json in qc_async according to latest updates in ITS track task: https://github.com/AliceO2Group/QualityControl/pull/1008/files

In addition, update of parameters for vertex plots.

### CODE REVIEW

**Review by chiarazampolli — COMMENTED** [review]
Seems fine to me! Thanks!

**Comment by chiarazampolli** [comment]
Do you need a change also for the json for MC?

**Comment by iravasen** [comment]
I think so, is it this one: https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/QC/json/its-clusters-tracks-qc.json ?

**Comment by chiarazampolli** [comment]
Yes. Please, keep them in sync for whatever should be the same in data and MC.
Thanks!! I am merging this one for now.

**Pull request merged**
