### PR TITLE
PHS QC and standalone calibration: pedestal and LED

### PR DESCRIPTION
**Pull request by sevdokim**
hello! PHS pedestal + standalone calibration added to DATA/standalone-calibration.desc

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Seems fine to me, just a confirmation: you are now enabling PHOS QC in sync data taking, right?

**Comment by sevdokim** [comment]
hello @chiarazampolli 
yes, I'm enabling PHOS QC in this PR. It is working at least on EPN nodes. Maybe you know how to test it in SYNCMODE and async reco?

**Comment by chiarazampolli** [comment]
Hello @sevdokim , 

For the SYNCMODE, you should simply use an updated code with your PR (once merged), right @davidrohr , @knopers8 ?
For the async reco, you already have a json here:
https://github.com/AliceO2Group/O2DPG/tree/master/DATA/production/qc-async
Since PHOS was not in the global runs that we use for async pass, you did not have any QC output. 

Cheers,

Chiara

**Comment by sevdokim** [comment]
Hi @chiarazampolli 
looking into qc-workflow.sh one can see EPNSYNCMODE and SYNCMODE. I've tested EPNSYNCMODE. But what is SYNCMODE?

**Comment by chiarazampolli** [comment]
SYNCMODE is when you run the full-system-test to run the sync reco steps, see https://github.com/AliceO2Group/O2DPG/blob/master/DATA/common/README.md. @davidrohr can confirm.

**Comment by sevdokim** [comment]
hello @chiarazampolli @davidrohr 
can this PR be merged or we need some additional workout?

**Comment by davidrohr** [comment]
fine with me for the calibration. But the PR also enables PHS QC, despite not being stated in the title. Is that intended?

**Comment by sevdokim** [comment]
hi @davidrohr 
sorry I forgot to mention PHS QC in the title. Done!

**Comment by davidrohr** [comment]
> Hi @chiarazampolli
> looking into qc-workflow.sh one can see EPNSYNCMODE and SYNCMODE. I've tested EPNSYNCMODE. But what is SYNCMODE?

@sevdokim : `SYNCMODE=1` = sync processing, `SYNCMODE=0` = async processing.
`EPNSYNCMODE=1` means sync processing on the EPN farm and is set automatically when running online.
When running sync processing as test on your laptop, it should be only SYNCMODE=1.

**Pull request merged**
