### PR TITLE
askOnceAllButField changed to true in the GeomHelper

### PR DESCRIPTION
**Pull request by chiarazampolli**
@shahor02 , @davidrohr , @knopers8

### CODE REVIEW

**Review by shahor02 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
> Thx! Can you check with @martenold to do an fst on the EPNs. Also the detectors must update their configs in consul, so please check with them as well.

Yes, we are updating. Only missing one is MFT (@tomas-herman , I pinged you also via mail)

**Comment by martenole** [comment]
Hi @chiarazampolli 
the FST on the EPNs is running stably with this change. The next software update is planned for Tuesday. Do we need to add the `askOnceAllButField` option to the json files at P2 synchronously again or has that already been done, do you know?

**Comment by chiarazampolli** [comment]
Hello, 
This is an optimization, if not there, it won't be critical, but better to have it. 
For GLO, I already changed it on Monday. ITS also did it (they added a log entry if I am not wrong). Can you check with MFT, and TOF?
Chiara

**Comment by tomas-herman** [comment]
Hi, for MFT I also put this option in the Consul already on Monday.

**Comment by martenole** [comment]
For TOF I still see it disabled. Who should I ping for the TOF QC json files?

**Comment by chiarazampolli** [comment]
I think @noferini can update consul for TOF.

**Pull request merged**
