### PR TITLE
Fixing cases in which the number starts with 0 and is considered base 8

### PR DESCRIPTION
**Pull request by chiarazampolli**
@shahor02 
I am still checking why I had `wc -l`...

### CODE REVIEW

**Comment by chiarazampolli** [comment]
In this case, `-l` gives a negative value --> so I take the substring from the end:
e.g.:
3027145464:-9 --> 027145464
`-c` gives a positive value, and it is used as offset for the substring:
e.g.:
3027145464:1 --> 027145464
So the net result is the same. 
I think that `-c` is better, because `-l` will always be 1, no matter the length of the proc_id.

**Comment by chiarazampolli** [comment]
Note that with this script, we don't get the last 10 or 9 digits, as in the comment, but the last 9 (base 32) or 8 (base 16). 
To get the last 10 (or 9), we could just use:
```
ALIEN_PROC_ID_OFFSET_INT32=$((10#${ALIEN_PROC_ID: -10}))
ALIEN_PROC_ID_OFFSET_INT16=$((10#${ALIEN_PROC_ID: -9}))
```
I will try with more time tomorrow.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , @davidrohr , 

This seems much better to me. Can you please check?

Chiara

**Comment by chiarazampolli** [comment]
Hello @davidrohr , @shahor02 , 

Any comment about this PR?

Chiara

**Comment by davidrohr** [comment]
I didn't test it, but fine with me

**Comment by shahor02** [comment]
Fine for me

**Pull request merged**
