### PR TITLE
[EMCAL-1054] Enable BC task in simulations

### PR DESCRIPTION
**Pull request by mfasDa**
Include EMCAL BC QC in simulations in case
CTP is included.

### CODE REVIEW

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/AliceO2/pull/12364, therefore handled as separate PR.

**Comment by mfasDa** [comment]
Results from local tests shown in https://github.com/AliceO2Group/O2DPG/pull/1352

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/QualityControl/pull/2060 in order to provide different trigger class names for min. bias triggers, or to allow an or of 2 min. bias trigger classes at the same time.

Reasons:
- Trigger class names were changing in time, we need to be able to allow different classes and match the with the corresponding trigger configuration of that run
- In pp we used 2 trigger classes as min. bias trigger (C0TVXTSC,C0TVXTCE), we need to be able to accept triggers if either of them fires.

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel , @noferini , 
The CI is full of 
```
8-Background generator seed:  825338745
9-Timeframe 1 seed:  825338746
10-o2dpg_sim_workflow: Error! Interaction rate not >0 !!!
11:[FATAL]: O2DPG_TEST Workflow creation failed
```
I am merging this one now. 
Chiara

**Pull request merged**
