### PR TITLE
New commit on ChiC1, ChiC2 to avoid duplicated included

### PR DESCRIPTION
**Pull request by amaringarcia**
This is the new commit. I had to include the definitions of the ChiC1, ChiC2 cocktail inside the GeneratorPromptCharmonia.C to avoid double include's

### CODE REVIEW

**Comment by amaringarcia** [comment]
async-mc

**Comment by amaringarcia** [comment]
@gconesab would it be possible to approve again? I have closed  the other commit

**Review by gconesab — APPROVED** [review]

**Comment by amaringarcia** [comment]
Dear all,
where can I find the test that is done during the checks? The check I did was: ${O2_ROOT}/share/scripts/jobutils2.sh; taskwrapper sgnsim_2.log '${O2_ROOT}/bin/o2-sim -e TGeant4 --skipModules ZDC -n 200 --seed 418581023 --field ccdb -j 8 \
-g external --configFile ${O2DPG_ROOT}/MC/config/PWGDQ/ini/Generator_InjectedChiCToElectronMidy_TriggerGap.ini -o sgn_2 \
--timestamp 1547161230000 --run 302001 --vertexMode kCCDB'

and the test was successful.
Regards,
Ana

**Comment by benedikt-voelkel** [comment]
Hej @amaringarcia 
please check this comment I made in another PR: https://github.com/AliceO2Group/O2DPG/pull/1504#issuecomment-1978400435

Specifically, here is a section on how to run tests locally: https://aliceo2group.github.io/simulation/docs/generators/generatorconfig.html#run-the-test-locally

In you case, it would concern this test: https://github.com/AliceO2Group/O2DPG/blob/master/test/run_generator_tests.sh

Please let me know in case you have any questions.

**Comment by amaringarcia** [comment]
> Hej @amaringarcia please check this comment I made in another PR: [#1504 (comment)](https://github.com/AliceO2Group/O2DPG/pull/1504#issuecomment-1978400435)
> 
> Specifically, here is a section on how to run tests locally: https://aliceo2group.github.io/simulation/docs/generators/generatorconfig.html#run-the-test-locally
> 
> In you case, it would concern this test: https://github.com/AliceO2Group/O2DPG/blob/master/test/run_generator_tests.sh
> 
> Please let me know in case you have any questions.

Dear @benedikt-voelkel , I have a technical question. I have looked at the macro to be created. But I have a question about the meaning of the command child0->getToBeDone()  and child1->getToBeDone()  Where can I find this?  

The decay for me is a bit different, as I go from ChiC-> J/psi +gamma. 

Thanks in advance,
Ana

**Comment by benedikt-voelkel** [comment]
What you refer to are methods of `MCTrack`, see here: https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/simulation/include/SimulationDataFormat/MCTrack.h

In particular `getToBeDone()` returns `true` if the track should be transported

**Comment by amaringarcia** [comment]
Dear all,
I have now created the macro that was needed for the test.
Best regards,
Ana

**Comment by benedikt-voelkel** [comment]
@amaringarcia Thank for pushing the macro. I will find out why all tests fail and get back to you.

**Comment by benedikt-voelkel** [comment]
Hello @amaringarcia 

I x-checked and this is what I did on my machine:

1. I fetched your branch
1. Loaded the environment
1. Inside the environment, do `export O2DPG_ROOT=/your/path/to/your/O2DPG`
1. run `O2DPG_TEST_REPO_DIR=${O2DPG_ROOT} O2DPG_TEST_HASH_BASE="HEAD~2" ${O2DPG_ROOT}/test/run_generator_tests.sh`

Then, it produces `o2dpg_tests/generators/<test_name>`
Each of those `<test-name>` directories has an `o2sim_serverlog` file and in there, the issue is
```
libEGPythia6.so.6.30.01: undefined symbol: pythia6_common_address
```

So you should definitely leave this line in: https://github.com/AliceO2Group/O2DPG/pull/1528/files#diff-8d9f270effbb76af6de76474d081f6b869bdb9ed3368e4502591e2cf46f47672L14

Does that help?
Can you try it? On my side, putting back that line, makes all the tests pass.

**Comment by benedikt-voelkel** [comment]
@AliceO2Group/reviewers-pwg-dq  could you take a look and approve? From my side, you can also go forward with the merge.

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
