### PR TITLE
Update MFTTracking param on setenv_extra.sh

### PR DESCRIPTION
**Pull request by rpezzi**
- Reduce number of cluster bins used for track-finding optimization. This increases MFT acceptance with a slight increase in reconstruction CPU cost.
- Remove obsolete configurations (which are defaults and should not change any more)

### CODE REVIEW

**Comment by rpezzi** [comment]
I checked this configuration for the PbPb test beam. There is a 20% increase in efficiency and 70% increase in tracking time. Therefore, for the time being I would like to keep this setting for both pp and PbPb.

**Review by chiarazampolli — COMMENTED** [review]
Hello @rpezzi , the increase by 70% is not too bad considering that privately you wrote me `it goes from 0.3 to 0.5 seconds per TF on my laptop`. But I would put a protection to enable this in pp or PbPb 22s only, just to not forget that it needs optimiazation for PbPb at nominal IR. What do you think?

**Comment by rpezzi** [comment]
Hi @chiarazampolli 

> I would put a protection to enable this in pp or PbPb 22s only

Sure. This is done. There is also one new parameter that improves chi^2 of MFT tracks, without any impact on CPU budget.

**Review by chiarazampolli — APPROVED** [review]

**Comment by rpezzi** [comment]
To clarify, the impact of changes introduced here:
- PbPb test beam, CPU time increases by a factor of 1.7.
- pp 500 kHz, CPU time increases by a factor 7. A previous result indicating a minor impact for pp was not representative of typical minimum bias conditions.

**Pull request merged**
