### PR TITLE
Align to recent changes and extension

### PR DESCRIPTION
**Pull request by njacazio**
@chiarazampolli @strogolo this for me worked on LHC22e data, I also added some improvement to the analysis script

### CODE REVIEW

**Comment by njacazio** [comment]
I also tested the multiplicity table and for me it works

**Comment by njacazio** [comment]
pinging also @benedikt-voelkel to check that this is to your taste

**Comment by benedikt-voelkel** [comment]
Hej @njacazio ,
shall we change all WFs to lists as you did for EventTrackQA? I will have a closer look tomorrow also

**Comment by njacazio** [comment]
> Hej @njacazio , shall we change all WFs to lists as you did for EventTrackQA? I will have a closer look tomorrow also

Now it works with both syntax I don't have opinions

**Comment by njacazio** [comment]
@strogolo if you could also crosscheck that it works it would be great

**Comment by chiarazampolli** [comment]
Thanks @njacazio , it looks ok to me but let's wait for @benedikt-voelkel . 
One question: the multiplicity task now worked with a dummy entry, or what exactly?

**Comment by njacazio** [comment]
> Thanks @njacazio , it looks ok to me but let's wait for @benedikt-voelkel . One question: the multiplicity task now worked with a dummy entry, or what exactly?

It works with the pr that avoids the fatal

**Comment by strogolo** [comment]
Hi @njacazio, the check I can do is the same you did...trying running the python script that you and Benedikt have put in O2DPG. Nevertheless, as long as the QC tasks do not check whether the object is empty or not, this solution can work. The issue might be when a check on the content of the object will be introduced...but it's not the current case.

@chiarazampolli: shall I stop the implementation of a dummy object (i.e. flat at unity)?

**Comment by chiarazampolli** [comment]
Ciao @strogolo , 
I would still prefer to have it, since we are currently running with old tags, where the change by Nicolo' to avoid teh fatal is not included. 
Chiara

**Review by benedikt-voelkel — APPROVED** [review]
Ok from my side, thanks @njacazio

**Pull request merged**
