### PR TITLE
start with numa scaler 1, will be set to real value on EPN

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Review by davidrohr — CHANGES_REQUESTED** [review]
See my comment in #1505 1505

**Comment by shahor02** [comment]
@davidrohr I don't see where the `RECO_NUM_NODES_WORKFLOW` and `NUMAGPUIDS` are defined, isn't parser running for epns only?

**Comment by davidrohr** [comment]
`RECO_NUM_NODES_WORKFLOW` is defined in dpl-workflow.sh, and `NUMAGPUIDS` is defined in setenv.sh, so both should be available.
And the default should not be 1, it should be 230. If you set it to one, it will assume it has to do the load of all EPN nodes, so will multiply multiplicities by 230 with some cuts.

Anyhow, I would just move up the `RECO_NUM_NODES_WORKFLOW_CMP` definition, as I remarked in Chiara's PR.

**Comment by shahor02** [comment]
ok, thanks

**Review by davidrohr — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Why did you add the labels? The problem was introduced by https://github.com/AliceO2Group/O2DPG/pull/1483, which is not in stable-async. 

Chiara

**Comment by shahor02** [comment]
I thought it should be ported. Removed the labels.

**Pull request merged**
