### PR TITLE
TOF: Add moving window in TOF asynch jsons

### PR DESCRIPTION
**Pull request by ercolessi**
This PR is to add moving window for asynch TOF objects:

DecodingErrors
HitMap
OrbitVsCrate
mEffPt_ITSTPC-ITSTPCTRD
EvTimeTOF
DeltaEvTimeTOFVsFT0AC

Cc @noferini

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@JianLIUhep , can you review? Thanks!

**Comment by JianLIUhep** [comment]
Yes, the code is good for me. 
I also understood from @ercolessi that the local test was successful. The memory size looks reasonable as Francesca updated in [the table](https://docs.google.com/spreadsheets/d/1_vCjDXfL7-oiEaUYSUTe2fpsxbb89ds-DDDql4KeIxU/edit?gid=0#gid=0). 
So, it's ok to merge on my side. @chiarazampolli

**Comment by ercolessi** [comment]
I confirm it was tested locally! Thanks

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
In [async-v1-01-12d](https://github.com/AliceO2Group/O2DPG/tree/async-v1-01-12d) for cpass0

**Pull request merged**
