### PR TITLE
ITS tracking: update PbPb params for apass1

### PR DESCRIPTION
**Pull request by mconcas**
@chiarazampolli : as discussed, I also added the label for apass4 of PbPb 2023 let me know if this does require more work.

### CODE REVIEW

**Comment by mconcas** [comment]
+async-label async-2024-pp-apass1 async-2023-pbpb-apass4

**Comment by chiarazampolli** [comment]
Ciao @mconcas , 

I think there was a misunderstanding: we should not port this to the PbPb 23 apass4 tag, actually, or it will spoil the MCs anchored to it. So I removed it. This will be taken for any future apass5 of PbPb 23.

Chiara

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Ciao @mconcas , 

There was another PR that I merged which touched the same file. Can you rebase to master? There seems to be no conflicts, but in the "files changed", I don't see the modifications from the other PR:

https://github.com/AliceO2Group/O2DPG/pull/1826/files

Do you know if it is normal? The same is true for https://github.com/AliceO2Group/O2DPG/pull/1828/files, @shahor02 . Maybe I am simply overcareful...

Chiara

**Comment by shahor02** [comment]
> Do you know if it is normal? The same is true for https://github.com/AliceO2Group/O2DPG/pull/1828/files, @shahor02 . Maybe I am simply overcareful...

@chiarazampolli this is because you merged your PR after I've opened mine. If my PR does not show the conflict with master, this means that the rebasing is not really necessary. But I've done it anyway.

**Comment by chiarazampolli** [comment]
Merged, failures unrelated.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Thanks! Matteo did not do the rebase, and we now have the evidence that it works :-) 

Thanks!

Chiara

**Pull request merged**
