### PR TITLE
Update of ITS jsons + added nthreads for ITS THR calibration wf

### PR DESCRIPTION
**Pull request by iravasen**
Changes applied:
- modified its jsons for data and MC to reflect changes in ITS QC: https://github.com/AliceO2Group/QualityControl/pull/1025 and https://github.com/AliceO2Group/QualityControl/pull/1007 
- added nthreads to threshold calib workflow following this PR: https://github.com/AliceO2Group/AliceO2/pull/8021

### CODE REVIEW

**Comment by davidrohr** [comment]
@iravasen : could you please rebase this branch on O2DPG master? This PR as is cannot be rebased and merged.

**Comment by iravasen** [comment]
@davidrohr sorry for that, can you see now? Thank you.

**Comment by davidrohr** [comment]
Now there is still a conflict, could you rebase on the master branch and solve the conflict?

**Comment by chiarazampolli** [comment]
Merging for the async pass3.

**Pull request merged**
