### PR TITLE
MC/config/PWGEM: add Generator.C and ini for LF->ee/gamma in PWGEM

### PR DESCRIPTION
**Pull request by dsekihat**
MC/config/PWGEM: add Generator.C and ini for LF->ee/gamma in PWGEM

### CODE REVIEW

**Comment by dsekihat** [comment]
Dear @benedikt-voelkel , I am not sure which label I should attach. At least, this is for MC production. Thank you.

**Comment by benedikt-voelkel** [comment]
@dsekihat it depends, would you like to have these available in the 2022 apass4 or apass6 of pp? Another reasonable label would be `async-2022-pp-apass6-2023-PbPb-apass2`

Otherwise, if these changes are only needed for very new upcoming productions (meaning the ones that will be run after rebasing the async software to `O2@dev` and `O2DPG@master`, at this point, no further labels need to be added.

**Comment by dsekihat** [comment]
Dear @benedikt-voelkel , Thank you for your reply. I want the new MC production anchored to LHC22o pass6 (and future passes).
I have another question. Who should approve this PR? PWG-reviews only or PWG-reviewers and DPG?

**Comment by benedikt-voelkel** [comment]
Since it affects the physics and is otherwise no technical developments on any DPG core tools, PWG reviewers should judge, review and merge.
And I also added the required labels for now.

**Comment by dsekihat** [comment]
Thank you very much!

**Review by ivorobye — APPROVED** [review]

**Pull request merged**
