### PR TITLE
Add MC/config for ALICE3 otf simulations

### PR DESCRIPTION
**Pull request by jesgum**
This pull request adds the `MC/config/ALICE3` directory to be used for on-the-fly simulations on hyperloop.
Contains config and ini files for different beams. Is currently being tested and will be marked ready very shortly. Input is already welcome now, thanks!

### CODE REVIEW

**Comment by ddobrigk** [comment]
@benedikt-voelkel @sawenzel this is to be used with the OTF simulations on hyperloop: we'd need the `ini` files to be with an O2DPG tag. Can you please take a look and if ok carry on? Many many thanks! tagging also: @mconcas @jgrosseo

**Comment by sawenzel** [comment]
Fine by me. Maybe we could just add a `README.md` in the `MC/config/ALICE3` saying that these configs are used in Hyperloop studies, etc?

**Comment by ddobrigk** [comment]
Yes that's very reasonable. @jesgum can you please take care of that? Thank you!

**Comment by jesgum** [comment]
It has now been added to the directory.

**Comment by sawenzel** [comment]
Good. I think now you need remove the draft status.

**Review by sawenzel — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
For this use case it would be fine to have dummy tests for the specific generators for now.
In any case, one basic test is anyway ran over the kinematics.

What is your opinion on that @sawenzel ?

**Comment by sawenzel** [comment]
A CI test would be a "nice to have". But since this is ALICE3 R&D, it is probably not obligatory for now.

**Review by benedikt-voelkel — CHANGES_REQUESTED** [review]

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
