### PR TITLE
Fix converter logic for o2-analysis-v0converter in test workflow

### PR DESCRIPTION
**Pull request by jezwilkinson**
Since o2-analysis-v0converter produces the v0_002 table, it should be checking for that and not O2v0_001 to decide whether to run the converter

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
fyi: Don't worry about the failed "Collect and print async labels" CI for now.

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
@jezwilkinson should this be contained in any of the production tags for async reconstruction/anchored MC? It would depend on whether the corresponding O2 developments for the `v0_002` table are contained in those tags. Do you know?

Otherwise, would the worst-case scenario be that the `v0_002` table would be simply overwritten the converter?

**Comment by jezwilkinson** [comment]
Hi @benedikt-voelkel ,
I am not sure if the script is actively used with a configuration that would be affected in the production pipeline so can't really speak to that. But the worst-case is a crash of the analysis testing workflow (reason for spotting this issue was some tests ongoing in the TPC reconstruction group that were failing - if the v0 converter tries to run with a missing v0s_001, as would be triggered before the change, then it will crash with a "missing tree" error)

**Comment by benedikt-voelkel** [comment]
To get back to this @jezwilkinson 
This is not yet included in the corresponding `async-2023-pbpb-apass3` software. However, I am not aware of any issues due to the fact that it is not included. Could you comment?
If for any reason strictly necessary, let's include it. Otherwise, could we also think about removing the label and not include it?
Thanks a lot!

**Comment by jezwilkinson** [comment]
as this was to fix a bug that @wiechula and @aschmah were encountering I leave it for them to comment whether it is still required

**Comment by wiechula** [comment]
It might be we only use it for the local testing. So I cannot really comment. If there we no issues reported up to now, I would guess not.

**Pull request merged**
