### PR TITLE
updated ITS json for QC async and MC according to QC PR1060

### PR DESCRIPTION
**Pull request by iravasen**
added parameter nBCbins to define the number of bins for plots showing bunch-crossing info. 
(ref: https://github.com/AliceO2Group/QualityControl/pull/1060/files)

### CODE REVIEW

**Comment by iravasen** [comment]
@chiarazampolli little update here to ITS jsons, PR1060 will be soon merged.

**Comment by chiarazampolli** [comment]
Thanks! I will wait for the other PR then.

**Comment by iravasen** [comment]
@chiarazampolli PR above has been merged by Piotr

**Comment by iravasen** [comment]
Hi @chiarazampolli yes, you can can

**Pull request merged**
