### PR TITLE
Adjust pp specific setting for primary vertexer

### PR DESCRIPTION
**Pull request by sawenzel**
Taken as suggested in https://alice.its.cern.ch/jira/browse/O2-2691

### CODE REVIEW

**Comment by sawenzel** [comment]
@gconesab @shahor02

**Review by shahor02 — COMMENTED** [review]
Hi @sawenzel 
The settings are ok but they should be used only for the pilot beam MC as many cuts/tolerances are relaxed to account for uncalibrated data. 
If the aim is to have general pp settings, then it should be 
```
{"pvertexer.acceptableScale2" : 9,
                       "pvertexer.dbscanMaxDist2" : 36,
                       "pvertexer.dbscanDeltaT" : 24,
                       "pvertexer.maxChi2TZDebris" : 100,
                       "pvertexer.maxMultRatDebris" : 1.,
                       "pvertexer.dbscanAdaptCoef" : 20.}
```

**Comment by sawenzel** [comment]
The aim was to satisfy the request made in the ticket https://alice.its.cern.ch/jira/browse/O2-2691. I didn't know this was for pilot beam only. In principle, I would prefer to put generic settings. The best would probably be to put into place CCDB objects for this as it will otherwise be difficult to maintain the code.
I can for now cheat and make the customization dependent on the run-number? What do you think?

**Comment by shahor02** [comment]
@sawenzel yes, eventually it will be set from the CCDB, but at the moment there is no custom query for such objects and I would not introduce them given that (hopefully) soon we will have DPL support for that.

**Comment by sawenzel** [comment]
reworked to contain generic pp settings as well exceptional ones for pilot beam MC run ranges 301000 - 301199.

**Pull request merged**
