### PR TITLE
[Anchor] Add some more help messages

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* help messages
* set ALIEN_JDL_ADDTIMESERIESINMC to a value at the beginning

### CODE REVIEW

**Comment by catalinristea** [comment]
Ciao @benedikt-voelkel, @chiarazampolli 

Just a short comment, regarding the use of ALIEN_JDL_ADDTIMESERIESINMC: if we do this in anchorMC.sh, then it will concern only the anchored MC, while we want it for any MC (common, PWG?) right?
Isn't it:
- Anchored MC: anchorMC --> o2dpg_sim_workflow_anchored --> o2dpg_sim_workflow.py
- Unanchored: o2dpg_sim_workflow.py
Couldn't this be done in the base script o2dpg_sim_workflow.py?

Thanks, Catalin.

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel , 
Why do you need a default? I mean, even without it, it will be ON if you don't specify anything different. 
Is this just more elegant? Or is there something I overlook?

Chiara

**Comment by benedikt-voelkel** [comment]
It's just for consistency. Of course it would not create problems but this relates somewhat to the "unbound issue" we had although - again - in this case, it would be fine.
But most importantly, I wanted to align things a little bit more and have everything that is somehow used at one place at the top of the file if that makes sense.

**Comment by chiarazampolli** [comment]
Sure, fine with me, I wanted to make sure that I did not miss anything, since I tagged already without this change.

**Comment by miranov25** [comment]
> Hello,
> 
> I don't think that this is needed in unanchored MCs. I would even think that unanchored is not needed at all anymore...
> 
> @miranov25, can you comment?
> 
> Chiara

I am not sure I understand the comment. For unanchored MC, the time series are indeed useless, but representatively sampled data are useful (I was checking it)
If the unanchored production is still used in the physical analysis for corrections, I would like to keep the representative sampling. I will check what happened in the jet production which I was running at GSI.

**Comment by benedikt-voelkel** [comment]
In any case, that is a different topic: For unanchored we would need to change different things.
Merging.

**Comment by chiarazampolli** [comment]
Unanchored should *not* be used for corrections, which is why i only applied the change to the anchoring script.

if needed, let’s take it in another pr.


Chiara

**Comment by chiarazampolli** [comment]
Label async-2023-pp-apass4 added to make the needed PR (https://github.com/AliceO2Group/O2DPG/pull/1686) apply

**Comment by chiarazampolli** [comment]
Tag for async-2023-pp-apass4 created, removing label.

**Pull request merged**
