### PR TITLE
Add asyn-label workflows for PRs

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
Following what was introduced in https://github.com/alisw/ali-bot/pull/1293

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@TimoWilken what do you think?
I hope I did everything correctly

**Comment by TimoWilken** [comment]
I think you may need to add the `pull-requests: write` permission to the top-level permissions block as well, not just the `jobs` block!

**Comment by TimoWilken** [comment]
Hm, I'm not sure, maybe you need `issues: write` as well? But then I don't know why it worked before...

**Comment by benedikt-voelkel** [comment]
Is it because it is run from my PR and not from upstream?

**Comment by benedikt-voelkel** [comment]
Merge to see if things work once they are in the upstream repo

**Pull request merged**
