### PR TITLE
Adjusting custom generators

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* use new interfaces to ensure proper
  * encoding of the HepMC and native status code
  * set tracking falg correctly

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
I propose we merge both this and the linked one at the same time so they go into the same tag.

**Comment by chiarazampolli** [comment]
I cannot merge in O2, @sawenzel , can you take care?

**Comment by davidrohr** [comment]
I merged the O2 one

**Comment by chiarazampolli** [comment]
Thanks @davidrohr !

**Pull request merged**
