### PR TITLE
Enable strangeness tracking by default

### PR DESCRIPTION
**Pull request by fmazzasc**
This ensures consistency between MC and data reconstruction conditions, where strangeness tracking is enabled by default both in pp and Pb--Pb

### CODE REVIEW

**Comment by fmazzasc** [comment]
+async-label async-2023-pbpb-apass, async-mc, async-2022-pp-apass6-2023-PbPb-apass2

**Comment by benedikt-voelkel** [comment]
@fmazzasc What is the runtime with strangeness tracking now? We saw a huge increase back then for PbPb when enabling strangeness tracking.

**Comment by fmazzasc** [comment]
Hi @benedikt-voelkel , in Pb--Pb the strangeness tracking takes ~ 20% of the total SVertexer timing, and it is included in all the reco passes (see for example https://alimonitor.cern.ch/users/download.jsp?view=true&path=/alice/data/2023/LHC23zzo/544961/apass3/0850/o2_ctf_run00544961_orbit0055391072_tf0000767622_epn020/stdout.log). 

If you want I can run Pb--Pb a simulation with and without it and tell you which is the overhead

**Comment by benedikt-voelkel** [comment]
If you could do so, it would be very useful to have a small comparison of the 2 scenarios.
Thanks @fmazzasc !

**Comment by fmazzasc** [comment]
Hi @benedikt-voelkel , 
I tested the SVertexer with and without the strangeness tracking on a MB Pb--Pb simulation (30 events,1 tf, 8 workers).

w/o strangeness tracking: `Timing: CPU: 12.08 Real: 3.25 s`
w/ strangeness tracking:   `Timing: CPU: 13.79 Real: 4.36 s`

**Comment by benedikt-voelkel** [comment]
For me, in principle, it is fine. It adds around 33% of time in the vertexing for PbPb and not a factor of ~8 which I think we have seen some months ago.
I do understand that this is somewhat necessary to make MC and data AODs compatible.
@sawenzel Do you agree that we take it and change the default as proposed here?

**Comment by sawenzel** [comment]
Fine for me. But in principle for anchored MC this setting (could / should) be picked up or transcribed from the reco settings automatically.

**Comment by benedikt-voelkel** [comment]
> Fine for me. But in principle for anchored MC this setting (could / should) be picked up or transcribed from the reco settings automatically.

That would be true if we would extract that in the workflow creation. Currently, we don't do that.
It's not even extracted at the moment: https://github.com/AliceO2Group/O2DPG/blob/master/UTILS/parse-async-WorkflowConfig.py#L147

**Comment by sawenzel** [comment]
> > Fine for me. But in principle for anchored MC this setting (could / should) be picked up or transcribed from the reco settings automatically.
> 
> That would be true if we would extract that in the workflow creation. Currently, we don't do that. It's not even extracted at the moment: https://github.com/AliceO2Group/O2DPG/blob/master/UTILS/parse-async-WorkflowConfig.py#L147

Yes, this is why I was including "should". It would be preferable to have this setting transcribed automatically. For now we can simply merge this PR.

**Comment by benedikt-voelkel** [comment]
I made the wrong assumption thinking that you mean it might be possible already somehow.
Merging now.

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
