### PR TITLE
Possibility to set the input specs for GLO QC dynamically, for K0s

### PR DESCRIPTION
**Pull request by chiarazampolli**
@shahor02 @f3sch

It was tested in the FST enabling the sec vtx:

```
export PRINT_WORKFLOW=1
export NHBPERTF=32
export SHMSIZE=8000000000
export NJOBS="$JOBS"
export DPL_REPORT_PROCESSING=1
export ARGS_EXTRA_PROCESS_o2_secondary_vertexing_workflow='--disable-cascade-finder --disable-3body-finder --disable-strangeness-tracker'

export WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO,MATCH_SECVTX,MATCH_TPCTOF 
export FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR 
export QC_REDIRECT_MERGER_TO_LOCALHOST=1 
export GEN_TOPO_WORKDIR=`pwd` 
export ALICE_O2SIM_DUMPLOG=1 
export NEvents=5 
export NEventsQED=100 
export O2SIMSEED=12345 
export QC_CONFIG_PARAM="--local-batch=QC.root"
$O2_ROOT/prodtests/full_system_test.sh
```

During the FST, there were issues with MFTdigits (when saving the QC output to file via the `--local-batch=QC.root` option) and also the TOF raw QC (which was then disabled).
For the FST, to enable sec vtx, I set:

`WORKFLOW_EXTRA_PROCESSING_STEPS=...MATCH_SECVTX,MATCH_TPCTOF `

where `MATCH_TPCTOF` can also be omitted. This same `WORKFLOW_EXTRA_PROCESSING_STEPS=...MATCH_SECVTX` would then be needed in online. 

Note that the reco_ASYNC in the FST also needs a change in the fst script, see https://github.com/AliceO2Group/AliceO2/pull/13770, since we need strangeness tracking in ASYNC for the AODs (disabled above by `export ARGS_EXTRA_PROCESS_o2_secondary_vertexing_workflow='--disable-cascade-finder --disable-3body-finder --disable-strangeness-tracker'`)

async reco was then tested on one run from zzo.

### CODE REVIEW

**Comment by shahor02** [comment]
@chiarazampolli why not putting the 

```
export ARGS_EXTRA_PROCESS_o2_secondary_vertexing_workflow='--disable-cascade-finder --disable-3body-finder --disable-strangeness-tracker'
export WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO,MATCH_SECVTX
```
to the `full_system_test.sh` (eventually, should go to dpl-workflow.sh). I would not add  `MATCH_TPCTOF ` since we don't want to run it online.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

I guess I have to, or it will not work (the CI fails). Another way is to switch off the K0s QC in the JSON for sync. 
Before that, I am actually trying to apply another modification: forcing the K0S QC to be off if there is no SECVTX. I need to test it. I will report here tomorrow.

For now, I am moving this PR to WIP.

Chiara

**Review by shahor02 — COMMENTED** [review]
OK, assuming that the `jq` manipulations are correct, I am not familiar with this.
BTW, `EPNSYNCMODE` implies  `SYNCMODE`, it is enough to check the latter.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Comparing lines 61 and 147 (where there are an "if"... "elif") it seems they are different. That is why we did like this. Should I remove ` SYNCMODE`?

Chiara

**Comment by shahor02** [comment]
`SYNCMODE` does not imply `EPNSYNCMODE`, but  `EPNSYNCMODE` means `SYNCMODE` running on the EPN. 
That said, checking both with OR does not hurt.

**Comment by chiarazampolli** [comment]
Checkes passed, merging.

**Pull request merged**
