### PR TITLE
add TOF cal in global workflow

### PR DESCRIPTION
**Pull request by noferini**
I created a new global production workflow for AliECS envirnoment where I added the first TOF sync-calibration prototype (tested in standalone mode).

The idea is to define here a variable (TOF_PROXY_OUTSPEC) to be used in O2(to be done) to set output proxy in the proper way.

Since there are no other example I did it in this way but if you prefer I do it in a different way let me know.

### CODE REVIEW

**Comment by noferini** [comment]
@davidrohr 
I would assume you review this PR (:))

**Comment by davidrohr** [comment]
Hi @noferini , thx, I see the point of this PR that we need to distinguish between the workflow with and without aggregator. I need to think about how to generalize this best, but just returned from vacation today and a lot of things have piled up, I'll reply some time next week. If you need it urgently, we can also merge this and adapt later if needed.

**Comment by noferini** [comment]
Hi David,
it is not urgent. I was trigger by P2 people which asked us when we think to port calibration in global runs.
I agree that we need to find the best general way. No problem for me to wait, I just wanted to start the discussion.

**Comment by chiarazampolli** [comment]
Should this not go here:
https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/calib-workflow.sh
?

**Comment by noferini** [comment]
I close, I'll reopen once ready

**Pull request closed without merging**
