### PR TITLE
MFT QC: Remove async task from sync QC. It is crashing, and anyway not sure if it should be there

### PR DESCRIPTION
**Pull request by davidrohr**
@tomas-herman : Is this async task supposed to be part of the sync QC?
In any case, this task is crashing and breaks the full system test on the EPNs.

### CODE REVIEW

**Comment by tomas-herman** [comment]
Hi @davidrohr , 

the async QC task is supposed to be part of sync QC. It has an old name but when @knopers8 and @Barthelemy rename the online QC tasks and checks it will be called Track task. 

As you can see here: https://github.com/AliceO2Group/O2DPG/blob/af386b9e1bcb69e6f01d3d9388010d20cc49fce1/DATA/production/qc-workflow.sh#L106-L110  we are using 2 QC workflows, one with track task and one without track task (in the current code still called async task). The corresponding json file is then selected. If this is crashing the full system test we need to find the issue and fix it. It could me some mistake in my PRs with the renaming if the other components were unchanged.

**Comment by davidrohr** [comment]
ok, then it is a bit poorly named :)
ok, will retry with that task, and try to get a stack trace. But if I can reproduce the crash, I'd remove it for now, and you can revert this once the issue is fixed.

**Comment by tomas-herman** [comment]
Yes, the name is really confusing at the moment so that is why we want to rename it to Track Task. But it was called async task for historical reasons as initially it was planned to run only in async...

Anyway, thanks for looking into it. We are running this workflows also at p2 from consul json files so if it is a mistake in the changes I did it will affect also the QC at p2 after the SW update on Monday.

**Comment by davidrohr** [comment]
@tomas-herman : I cannot reproduce it any more now, but I also updated QualityControl to the tag that was released today. Can it be that it would have crashed with the old QualityControl?

**Comment by davidrohr** [comment]
seems to work with new QC

**Comment by tomas-herman** [comment]
> @tomas-herman : I cannot reproduce it any more now, but I also updated QualityControl to the tag that was released today. Can it be that it would have crashed with the old QualityControl?

Yes, it would have failed with the old QC.

**Pull request closed without merging**
