### PR TITLE
PWG-LF: Update the resonance injection table

### PR DESCRIPTION
**Pull request by BongHwi**
- Xi1820s are added
- Add new injection script - Exotic resonances (f0, f1, glueball candidates)

### CODE REVIEW

**Comment by BongHwi** [comment]
The test will fail until we have the new PR on AliceO2.
I'm waiting for the merge of the current PR https://github.com/AliceO2Group/AliceO2/pull/12896 (I need one more PR after this)

**Comment by BongHwi** [comment]
@benedikt-voelkel Okay, the test has been passed. Can we merge this?

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by BongHwi** [comment]
Thanks, do we need to add the label?

**Comment by benedikt-voelkel** [comment]
That depends on you.
Do you want to have that in the next production tag, pp or PbPb? In that case, please add the labels.

**Comment by BongHwi** [comment]
I'd like to put the labels for `async-2022-pp-apass4`, `async-2023-pbpb-apass`, `async-2023-pp-apass1`, `async-mc`.

But, I can't modify the label in the PR. Perhaps it's not allowed for all.

**Comment by benedikt-voelkel** [comment]
See the comment at the beginning of the PR.
I will do it now.

**Comment by benedikt-voelkel** [comment]
+async-label async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc

**Comment by BongHwi** [comment]
Great, I found it. thanks!

**Pull request merged**
