### PR TITLE
Add configuration pbpb, update configuration pp

### PR DESCRIPTION
**Pull request by cpuggion84**
- Add new configuration for PbPb  -> Change histogram bin based on calibrations -> zdcPbPb.json
- Modify configuration pp ->Configuration without calibration. to be used as default except in PbPb  -> zdc.json
- qc-workflow.sh -> added beamtype check, for automatic configuration file selection.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @cpuggion84 , 

Thanks! Does this need an update in QC? If so, which PR?
Are you adding new histograms or increasing the number of bins? As reported to the mailing list, we need a careful evaluation of the QC output. How large is the ZDC?

Thanks,

Chiara

(@noferini )

**Comment by cpuggion84** [comment]
> **REQUEST FOR PRODUCTION RELEASES:** To request your PR to be included in production software, please add the corresponding labels called "async-" to your PR. Add the labels directly (if you have the permissions) or add a comment of the form (note that labels are separated by a ",")
> 
> ```
> +async-label <label1>, <label2>, !<label3> ...
> ```
> 
> This will add `<label1>` and `<label2>` and removes `<label3>`.
> 
> **The following labels are available** async-2022-pp-apass4 async-2023-pbpb-apass async-2023-pp-apass1 async-data async-mc async-2022-pp-apass6
async-2023-pbpb-apass3

**Comment by cpuggion84** [comment]
> Hello @cpuggion84 ,
> 
> Thanks! Does this need an update in QC? If so, which PR? Are you adding new histograms or increasing the number of bins? As reported to the mailing list, we need a careful evaluation of the QC output. How large is the ZDC?
> 
> Thanks,
> 
> Chiara
> 
> (@noferini )

Hi Chiara,
PR async-2023-pbpb-apass3
We use the same task for the asynchronous QC as for the synchronous QC running on P2. Previously, changes had been made in the QC task.  The changes are included in the release QC v1.135.
in the QC task: We removed two histograms and Added 4 histograms.
in the QC task: we have added new parameters to be able to more accurately set the number of histogram bins.
zdc.json configuration file: The new parameters were simply added . There was no significant change to the histogram bins.
zdcPbPb.json : In order to have histograms compatible with the calibrations, it was necessary to modify the bin and range of some histograms. In some cases the bin has been reduced, in others it has been slightly increased.
Cheers
Carlo

**Comment by chiarazampolli** [comment]
Hello, 

I can merge this PR, but we need to know the changes in QC to make it work in async reco. So before doing so, I would prefer that we clarify for QC. 

Chiara

**Comment by cpuggion84** [comment]
> Hello,
> 
> I can merge this PR, but we need to know the changes in QC to make it work in async reco. So before doing so, I would prefer that we clarify for QC.
> 
> Chiara

Hi Chiara, 

These are the detailed changes to the QC code:

These changes are affects also in async:
ZDCRecDataTask.h remove include as suggestion during review, remove summary plots ADC and TDC
ZDCRecDataTask.cxx remove include as suggestion during review, Review the reset() and the start/endOfActivity in the Tasks, change title of ADC histo, Added new parameters for ZEM, Added new correlection, Added ZEM ZP correlations, remove summary plots ADC and TDC, replaced .compare(...) with == as suggestion during review

These other changes instead only affect the qc at P2, I report them for completeness.
ZDCTaskRawData.json Apply QC naming convention, Apply proposed configuration changes in Consul to all the config files.
ZDCTaskRecData.json Apply QC naming convention, Apply proposed configuration changes in Consul to all the config files. Added new parameters for ZEM
PostProcessingConfigZDC.h remove template as suggestion during review
PostProcessingConfigZDC.cxx remove template as suggestion during review
ZDCRecDataCheck.cxx chech null pointer object as suggestion during review, replaced .compare(...) with == as suggestion during review
ZDCRawDataTask.cxx remove include as suggestion during review, Review the reset(), and the start/endOfActivity in the Tasks, review destructor, replaced .compare(...) with == as suggestion during review
ZDCRawDataCheck.cxx chech null pointer object as suggestion during review, replaced .compare(...) with == as suggestion during review


I provide the link to the qc pull request for more details https://github.com/AliceO2Group/QualityControl/pull/2138

**Comment by cpuggion84** [comment]
> QC v1.135

I Update it

**Pull request closed without merging**
