### PR TITLE
First round of pythonising and args consistency

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* pythonise if-else

* add required types to cmd args

* use '--' consistently for optional args

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@sawenzel @chiarazampolli @catalinristea 
Especially the cmd args are confusing in the sim WF.
At the same time I adjusted some overhead in `if-else` statements for now to enhance the code (readability)

**Comment by sawenzel** [comment]
As much as I like this, I think it will unfortunately be quite disruptive in many places (especially for scripts maintained outside of O2DPG). Should be done together with updating all production scripts.

**Comment by benedikt-voelkel** [comment]
Let me try to have both the `-<long-option>` and the `--<long-option>` and we issue a deprecation warning when people use the first way.
So I will update this PR soon.
At the same time we notify people so that in a few weeks-months from now we can actually remove the `-<long-option>`

**Comment by benedikt-voelkel** [comment]
Deprecation warnings added when using arguments like `-<long-arg>` (only single dash). The functionality shall eventually be removed together with the deprecated args.

**Comment by benedikt-voelkel** [comment]
close for now, can easily be re-opened and updated

**Pull request closed without merging**
