### PR TITLE
Updates to reduce memory consumption and allow DPG to turn off sampling in validation

### PR DESCRIPTION
**Pull request by lauraser**

### CODE REVIEW

**Comment by lauraser** [comment]
+async-label async-data

**Comment by lauraser** [comment]
Hi @chiarazampolli , I am contacting you due to the above message about the label association.

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @lauraser , 
I added the labels for you. 
@benedikt-voelkel , will Laura be able to add labels from now on? Even if I don't think that this is her first PR in O2DPG. Does she miss something?
Chiara

**Comment by chiarazampolli** [comment]
Merging without waiting for further tests since this is for async data reco only.

**Comment by benedikt-voelkel** [comment]
@chiarazampolli yes, now labels can be added by @lauraser .
It is only blocked in case of first-time contributions.

**Comment by chiarazampolli** [comment]
Perfect, thanks! Even if Laura already had PRs:

https://github.com/AliceO2Group/O2DPG/pulls?q=is%3Apr+author%3A%22lauraser+%22+is%3Aclosed

Chiara

**Comment by benedikt-voelkel** [comment]
Mh, you are right. I will follow this up in case it happens again.

**Pull request merged**
