### PR TITLE
dynamically manipulating always the local json file in GLO QC, for K0s

### PR DESCRIPTION
**Pull request by ehellbar**
and minor formatting changes (spaces instead of tabs)

this is required to make #1834 work also in online
- downloading the json from apricot to local and adding it to the `JSON_FILES`
  - when using local jsons to begin with, they are also added to `JSON_FILES` in the `add_QC_JSON` function
- manipulating the local json taken from `JSON_FILES` and store it in a temporary file
- replace the initial local json with the manipulated temporary file in `JSON_FILES`

**please do not merge yet, should be tested in online first**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hi @ehellbar , 

I assume the changes are needed since something in online did not work. I tested both FST and async reco, and there all was fine.

Chiara

**Comment by shahor02** [comment]
In the online topology creation, the consul path was treated as a local file.

**Review by shahor02 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Ok, thanks!

**Comment by ehellbar** [comment]
tested in online on STG, works.

**Pull request merged**
