### PR TITLE
use default MCH cluster resolution

### PR DESCRIPTION
**Pull request by pillot**
The default value is ok with the new alignment. Beside, I am going to remove this option to add 2 new ones for setting the resolution in x and y directions separately.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @pillot , 
I could merge this PR, but we are still processing apass2 (for which the new MCH alignment is not there, see https://alice.its.cern.ch/jira/browse/O2-3514?filter=-3). If we change tag to fix the remaining runs, this will be taken. Would it be ok?
Otherwise, we need to wait till apass2 is completed.
Chiara

**Comment by pillot** [comment]
Hi @chiarazampolli ,
Indeed, I missed that the tag could change for the apass2 and this be taken. Better to wait till apass2 is completed then.
Thanks!

**Comment by chiarazampolli** [comment]
Hello @pillot ,

agreed, but please, remind me to merge before apass3.

chiara

**Comment by chiarazampolli** [comment]
Hello @catalinristea , @pillot , @shahor02 , @noferini . 
I would merge this now, if you agree, because the remaining apass2 will not change tag (unless Catalin you want to try https://github.com/AliceO2Group/AliceO2/pull/10712 for low IR pp, but I would not). 
Let me know what you think.
Since the RelVal will be on 22m, and 22m is not affected by the new alignment, I guess this change is not needed there. @pillot , can you confirm?

**Comment by pillot** [comment]
Yes, it is not needed for the RelVal, although it would also work fine with it.

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
