### PR TITLE
[QC-810] Rename QC postprocessing tasks

### PR DESCRIPTION
**Pull request by knopers8**
@mfasDa @njacazio Are you fine with applying the proposed post-processing task naming convention to your tasks?

### CODE REVIEW

**Comment by mfasDa** [comment]
@knopers8 fine with me for EMCAL

**Comment by knopers8** [comment]
@njacazio @noferini @ercolessi is it fine also for `TOFTrendingHits`?

**Comment by ercolessi** [comment]
Hi @knopers8 yes ok for TOF!

**Comment by knopers8** [comment]
@chiarazampolli could you approve (or reject) please?

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
