### PR TITLE
ZDC: Add configuration file PbPb, modify configuration file pp, add s…

### PR DESCRIPTION
**Pull request by cpuggion84**
*  Add new configuration for PbPb -> Change histogram bin based on calibrations, reduced the number of histogram bins -> zdcPbPb.json
 * Modify configuration pp ->Configuration without calibration. to be used as default except in PbPb, reduced the number of histogram bins -> zdc.json
 * qc-workflow.sh -> added beamtype check, for automatic configuration file selection.

### CODE REVIEW

**Comment by cpuggion84** [comment]
Dear,
I don't have permissions to add labels. it's possible to add the label async-2023-pbpb-apass4

**Comment by cpuggion84** [comment]
QC version >= U v1.135

**Review by chiarazampolli — DISMISSED** [review]

**Comment by JianLIUhep** [comment]
Looks good to me as well.

**Comment by cpuggion84** [comment]
+async-label async-2023-pbpb-apass4

**Review by knopers8 — COMMENTED** [review]
the same suggestions as in the ZDC QC review: https://indico.cern.ch/event/1344916/

**Comment by chiarazampolli** [comment]
Hello @cpuggion84 , 

Have you checked the suggestions by Piotr?

Cheers,

Chiara

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @cpuggion84 ,

I don't know know if you implemented Piotr's suggestions, but since we're starting apass4, I am merging. This is risky, as the PR was not tested. Please, keep an eye to the production. If it won't work, we'll need to act fast, which could mean to disable the ZDC QC.

Chiara

**Comment by chiarazampolli** [comment]
This PR is broken, it needs to be reverted ASAP, @cpuggion84 , as discussed via mail. 
Please, take action. Since I will be away from this late afternoon, I might not manage to do so (@JianLIUhep , @alcaliva , maybe you can do it if there is no answer by @cpuggion84 ?)

**Comment by alcaliva** [comment]
yes, I will keep an eye on it

**Pull request merged**
