### PR TITLE
PWGHF: for prod. of muons from b/c with different acceptance at quark level and w/ & w/o triggering on muons 

### PR DESCRIPTION
**Pull request by NicoleBastid**

### CODE REVIEW

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
Approval from @AliceO2Group/reviewers-pwg-hf will merge this automatically

**Comment by NicoleBastid** [comment]
+async-label async-2022-pp-apass7

**Comment by alcaliva** [comment]
hi @fgrosa , is this PR needed for a MC production anchored to apass7? how urgent is it? should this run over Christmas? Thanks

**Comment by alcaliva** [comment]
ported to async-v1-01-02g

**Pull request merged**
