### PR TITLE
Enable IU analyses in trackQC (AnalysisQC).

### PR DESCRIPTION
**Pull request by mfaggin**

### CODE REVIEW

**Comment by mfaggin** [comment]
@rolavick with this PR we should have the `IU` outputs also from the AnalysisQC.

**Comment by mfaggin** [comment]
@sawenzel @chiarazampolli @benedikt-voelkel @gconesab

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Fine with me. @benedikt-voelkel ?

**Comment by mfaggin** [comment]
> Fine with me. @benedikt-voelkel ?

@benedikt-voelkel any news?

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
