### PR TITLE
[GenTest] Always include partonic event

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Some tests that need parsonic information might otherwise break

**Comment by benedikt-voelkel** [comment]
@gconesab can you merge this?

**Comment by gconesab** [comment]
> @gconesab can you merge this?

I am not sure it leaves me to merge it.

**Comment by benedikt-voelkel** [comment]
maybe @chiarazampolli can merge is? :)

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
