### PR TITLE
Randomise PDG code

### PR DESCRIPTION
**Pull request by lbariogl**

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
I will have a look tomorrow to check why this CI fails.

**Comment by benedikt-voelkel** [comment]
Hej @TimoWilken 
This is the first time I see this error in the sim CI. Do you know anything by any chance?
`SimulationDataFormats` also hasn't changed in the last months and until today, there have been various CIs here with this Monte Carlo script as well as with others.
I also don't seem to see any possibly related changes in O2 or alidist 🤔 

Could it be helpful to rerun the CI when we have a chance that it will run against another version of O2 (more recent)?
If the problem persists, I will take a deeper look.

**Comment by benedikt-voelkel** [comment]
Thanks fir of all for fixing the typo @lbariogl 

Now, I see this in the log:
```bash
Following INI files will be tested:
  - MC/config/PWGLF/ini/GeneratorLFHyperNucleippGap.ini
  - MC/config/PWGLF/ini/GeneratorLFHypertritonPbPbGap.ini
  - MC/config/PWGLF/ini/GeneratorLFHyperNucleiPbPbGap.ini
  - MC/config/PWGLF/ini/GeneratorLFHypertritonppGap.ini
Test 1: /O2DPG/MC/config/PWGLF/ini/GeneratorLFHyperNucleippGap.ini with generator External[0;31m -> FAILED[0m
Test 2: /O2DPG/MC/config/PWGLF/ini/GeneratorLFHypertritonPbPbGap.ini with generator External[0;32m -> PASSED[0m
Test 3: /O2DPG/MC/config/PWGLF/ini/GeneratorLFHyperNucleiPbPbGap.ini with generator External[0;32m -> PASSED[0m
Test 4: /O2DPG/MC/config/PWGLF/ini/GeneratorLFHypertritonppGap.ini with generator External[0;32m -> PASSED[0m
[0;31mError found in log /sw/BUILD/549843a13031d84f712e4e1a9deca57bda60693a/O2DPG-sim-tests/o2dpg-sim_tests/o2dpg_tests/generators/1_GeneratorLFHyperNucleippGap.ini_External_dir/o2dpg-test-kine.log[0m
1-### Testing /O2DPG/MC/config/PWGLF/ini/GeneratorLFHyperNucleippGap.ini with generator External ###
2-
3-Processing External.C...
4---------------------------------
5-# Events: 100
6-# Injected nuclei 
7-1000010020: 1
8-# Injected nuclei 
9--1000010020: 0
10-No generated: -1000010020
11:(int) 1
```

Have you tried to run the tests locally as well to x-check?

**Comment by lbariogl** [comment]
Hi @benedikt-voelkel, tests are failing because the injected particle is selected randomly from a list, so it can happen that a state is not there in 100 events (with one injection every five events). I will fix the test to work with this.

**Comment by benedikt-voelkel** [comment]
@TimoWilken it seems that there are no logs for the simulation CI. Do you know what might have gone wrong?

**Pull request merged**
