### PR TITLE
PWGHF: update values in .ini and update generator

### PR DESCRIPTION
**Pull request by ZFederica**
- update argument values in .ini file for Xic and Omegac generator
- update HF generator to trigger either on quark or on hadron

Hello @fgrosa and @ddobrigk, what do you think about the change in the generator?

### CODE REVIEW

**Comment by fgrosa** [comment]
> * update argument values in .ini file for Xic and Omegac generator
> 
>     * update HF generator to trigger either on quark or on hadron
> 
> 
> Hello @fgrosa and @ddobrigk, what do you think about the change in the generator?

Hi @ZFederica is there a reason to remove the trigger on the quark? If you want both charm and beauty I think that the best would be to have two productions, one with a trigger on beauty quarks + Xic and the other one with a trigger on charm quarks + Xic (otherwise anyway you will have a charm dominated sample and to get a decent statistics for beauty you should simulate much more charm than needed). In general, if there is a good point for having it, it would be good to have an option to turn the trigger on the quark off and not to have it always off when you require an hadron.

**Comment by ZFederica** [comment]
Ok, I removed the change in the generator, now in this PR there is only an update of some values in my .ini files

**Comment by benedikt-voelkel** [comment]
I assume this PR is ready for review/merge, right @ZFederica? However you are saying 

> This is a temporary solution to have this option available, further studies are needed to propose a final version.

so just to be sure: Is there anything else expected here?

**Comment by ZFederica** [comment]
Hi @benedikt-voelkel, yes this PR is ready to be merged, thanks!

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
