### PR TITLE
Improving content of AODs merging DFs

### PR DESCRIPTION
**Pull request by chiarazampolli**
@jgrosseo

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Seems to not work perfectly for now, this is why it is [WIP]

**Comment by chiarazampolli** [comment]
@jgrosseo , if you agree, I will merge this. I tested it, and it worked: initial AO2D file had 250 DFs, final one had 125. 
Pinging also @catalinristea .

**Comment by chiarazampolli** [comment]
Merged, to have it in the tag tonight.

**Comment by jgrosseo** [comment]
Looks good!

**Pull request merged**
