### PR TITLE
Streamline LF injector/GT, add eta window trigger

### PR DESCRIPTION
**Pull request by njacazio**
@ChiaraDeMartin95 discussed this morning
@BongHwi please consider this as well in the .gun files

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
@TimoWilken do you think we can re-run the CI? Somehow, there was no O2DPG in the `BUILD` directory. I think I saw this in the past.
I will put on my list to try to circumvent that in some way.

**Comment by gconesab** [comment]
Hi @benedikt-voelkel, I do not think the new error is "real" and maybe related to the failures seen in other commits, what do you think?

**Comment by benedikt-voelkel** [comment]
The CI ran. Now, the status is that there are issues in the macros as far as I can see.

**Comment by njacazio** [comment]
> The CI ran. Now, the status is that there are issues in the macros as far as I can see.

Hi @benedikt-voelkel indeed, I needed to add a checker and fix other minor issues, let's see CI now

**Comment by njacazio** [comment]
@benedikt-voelkel I checked the ci and it seems unrelated, can you confirm?

**Comment by benedikt-voelkel** [comment]
@TimoWilken Is this CI still running or is it stuck? Seems to me to take an unreasonable amount of time?!

**Comment by TimoWilken** [comment]
Hi @benedikt-voelkel, sorry, fixed now!

**Comment by benedikt-voelkel** [comment]
Good for merging @njacazio ?
Anything to add?

**Comment by njacazio** [comment]
A big thank you maybe :)

**Pull request merged**
