### PR TITLE
Bug fix for sampling

### PR DESCRIPTION
**Pull request by chiarazampolli**
@matthias-kleiner

### CODE REVIEW

**Comment by miranov25** [comment]
trying to subscribe ...

**Comment by miranov25** [comment]
Could you clarify which datasets were impacted by the bug? Was it confined solely to the triggered data productions?

Best regards,

Marian

**Comment by chiarazampolli** [comment]
Ciao @miranov25 , 
No dataset since we have no production done with this change. If you see any problem with this change, let me know, otherwise I will merge it.
Chiara

**Comment by chiarazampolli** [comment]
Hello Marian, 
The `ARGS_EXTRA_PROCESS_o2_tpc_time_series_workflow` is used to add extra options to workflow. What matters in this PR is the change in the env var used for the fraction: without this `ALIEN_JDL_SAMPLINGFACTORTIMESERIES` will be taken, which is a bug.

**Comment by chiarazampolli** [comment]
Merged.

**Pull request merged**
