### PR TITLE
Avoid complete randomness by default

### PR DESCRIPTION
**Pull request by mpuccio**
This is helpful to try to reproduce locally things that happen on the grid

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Actually, what we might want to do is setting different seeds for different TFs. Because atm the same seed is set for each TF and so event generation is "the same" for all of them. Would that make sense?

**Comment by mpuccio** [comment]
Very good point, I added the TF number to the default seed with the new patch. Benedikt, Chiara, let me know if you have any other comments

**Comment by chiarazampolli** [comment]
Seems fine to me. @benedikt-voelkel , any further comment?

**Comment by benedikt-voelkel** [comment]
It looks good to me @chiarazampolli @mpuccio

**Pull request merged**
