### PR TITLE
 adding ChiC1, ChiC2 cocktail to DQ

### PR DESCRIPTION
**Pull request by amaringarcia**

### CODE REVIEW

**Comment by crisjahnke** [comment]
Dear @noferini @chiarazampolli @gconesab we would like to ask you if it is possible to have a look on this commit from @amaringarcia and approve for the ChiC1, ChiC2 cocktail analysis.

**Comment by gconesab** [comment]
I can approve, but not my role in principle. I will if others agree.

**Comment by noferini** [comment]
Dear @gconesab , fine with me.
Cheers,
Francesco

**Review by gconesab — APPROVED** [review]

**Comment by amaringarcia** [comment]
I have solved the problem now, but it is easier for me to make a new pull request and close this one

**Pull request closed without merging**
