### PR TITLE
Adding eta cuts to the trigger

### PR DESCRIPTION
**Pull request by mbroz84**
Eta cuts in the trigger to have all daughter particles in the acceptance of muon or cent barrel.

### CODE REVIEW

**Comment by mbroz84** [comment]
The tests are failing due to
`4987-G__O2MathUtils dictionary forward declarations' payload:19:41: note: previous definition is here`
`4988-namespace o2{namespace math_utils{using Rotation2Df_t = Rotation2D<float>;}}`

Doesn't seem to have something with this PR.

**Comment by sawenzel** [comment]
Tested locally. Appears to be fine. Merging.

**Comment by mbroz84** [comment]
+async-label async-2023-pbpb-apass4

**Comment by chiarazampolli** [comment]
Ported to async-v1-01-18, label removed.

**Pull request merged**
