### PR TITLE
PWGLF: fix generator to produce anti-particles

### PR DESCRIPTION
**Pull request by ZFederica**
Change in generator_pythia8_box.C: modified id of particle to be generated in order to allow also for anti-particles production

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Comment by ZFederica** [comment]
Hello @gconesab , I noticed that the build check failed but I do not understand how this could happen: I made a minor change - as you can see in the Files changed tab - which should not cause any problem. Do you have any idea of what can be the cause?

**Comment by benedikt-voelkel** [comment]
That is a feature: The macro you changed is included in the `ini` files that were tested.
The tests are designed to not only be triggered when `ini` files are changed but also when related macros are changed...

**Comment by benedikt-voelkel** [comment]
Hej @ZFederica 
the tests look fine now. Is there anything else to expect for this PR? Otherwise, it seems ready to be merged now?!

**Comment by ZFederica** [comment]
Hi @benedikt-voelkel, there is nothing to be added to this PR, it's ready to be merged, thanks!

**Pull request merged**
