### PR TITLE
Enable MCHistograms and EventSelectionQC

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @gconesab Tested and we have someone who takes care of those analyses

**Review by gconesab — APPROVED** [review]

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel ,

should i merge before the tests?

chiara

**Comment by benedikt-voelkel** [comment]
@chiarazampolli ok for me. The changes are minimal and trivial.
At the moment the tests seem somehow stuck and not start.

**Comment by chiarazampolli** [comment]
Sorry, I did not see it yesterday evening. Merged now, but it will go in tonight's tag only.

**Pull request merged**
