### PR TITLE
[WIP] Initial commit of RSN injector for pp

### PR DESCRIPTION
**Pull request by BongHwi**
Developed with @njacazio 

The first commit of the MC injector of Resonance particles in the pp collision system.
Injected resonances:
- K*
- K*pm
- phi
- f_0(980)
- f_0(1370)
- f_0(1500)
- f_0(1710)
- rho(770)
- rho(770)pm
- Sigma(1385)+
- Sigma(1385)-
- Xi(1530)0
- Xi(1820)0
- Xi(1820)-0

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hej @BongHwi 
could you tell me quickly what the status of this PR is? Are you planning to add further modifications?

**Comment by chiarazampolli** [comment]
Hello @BongHwi , 
Can we then move this PR to WIP?
Chiara

**Comment by BongHwi** [comment]
Hello @chiarazampolli 
Yes,  please.

**Comment by BongHwi** [comment]
I'll open a new PR.

**Pull request closed without merging**
