### PR TITLE
Set CALIB_RCT_UPDATER to 0 if disabled

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Review by martenole — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
In async, we now have:
```
/cvmfs/alice.cern.ch/el9-x86_64/Packages/O2DPG/daily-20240409-0200-1/DATA/common/setenv_calib.sh: line 253: CALIB_RCT_UPDATER: unbound variable
```
Does this PR fix it? Yesterday I did not see it in my tests, it must have been something that sneaked in after I updated to dev in the morning. 
Chiara

**Comment by davidrohr** [comment]
@chiarazampolli : Yes, it should fix it. A fix for a problem at P2 which was commited yesterday was incomplete.

**Comment by chiarazampolli** [comment]
Ok, then I need to wait for a new build for async... 
I merged my PR since with my dev (from yesterday morning) all was good. Was this not spotted in any CI?

**Comment by shahor02** [comment]
What was the problem at P2? Adding RCT_UPDATER passed fullCI.

**Pull request merged**
