### PR TITLE
Heavy-flavour enhanced dielectron MCs

### PR DESCRIPTION
**Pull request by rbailhac**
Further script and fix for the heavy-flavour enhanced dielectron MC production.

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
Dear @rbailhac 
I will come back to you shortly about the failed generator test to let you know what is going on.

**Comment by rbailhac** [comment]
Dear Benedikt, 

I have finally here a first version of test macro for the three PWG-EM ini files (first). Please let me know what I should improve or let see at the results of the test.

For the others, I would need to see what they are exactly doing. It is true that I change one trigger function they are using but with default parameter this should not change anything.

Best regards,

Raphaelle

**Comment by benedikt-voelkel** [comment]
Hello @rbailhac ,
thanks a lot for taking care of some tests already! 

On the plus side: the tests were run.
On the minus side: They failed due to some requirement you made:
`The number of leptons in acceptance should be at least equaled to the number of events.`

I will send you some details via email to follow up on the technicalities of the tests so that we can keep the discussion here to the very central parts of your physics implementations.

**Comment by benedikt-voelkel** [comment]
@rbailhac @gconesab 
I checked the logs, they now look as expected: All tests implemented in this PR pass successfully, see below
From my side, it looks all good.
For the other INI files, we can follow a step-by-step approach over the coming days, what do you think @rbailhac ?


```bash
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbar_Psi2S_midy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbar_Psi2S_midy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbar_fwdy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbar_fwdy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbarToMuonsSemileptonic_fwdy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbarToMuonsSemileptonic_fwdy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbar_midy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbar_midy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_ccbarToMuonsSemileptonic_fwdy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_ccbarToMuonsSemileptonic_fwdy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbarToBplus_midy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbarToBplus_midy.ini[0m
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGDQ/ini/tests/GeneratorHF_bbbar_Psi2S_fwdy.C not defined for ini file /O2DPG/MC/config/PWGDQ/ini/GeneratorHF_bbbar_Psi2S_fwdy.ini[0m
Test 2: /O2DPG/MC/config/PWGEM/ini/GeneratorHF_ccbarToDielectrons.ini with generator External[0;32m -> PASSED[0m
Test 3: /O2DPG/MC/config/PWGEM/ini/GeneratorHF_bbbarToDielectrons.ini with generator External[0;32m -> PASSED[0m
```

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
