### PR TITLE
add protections and exit in case of missing parameters, remove defaul…

### PR DESCRIPTION
**Pull request by gconesab**
…t value of generator

### CODE REVIEW

**Comment by gconesab** [comment]
Hi, @sawenzel and @preghenella, let me know what you think

**Comment by sawenzel** [comment]
Ok with me. But can you test it with https://github.com/AliceO2Group/O2DPG/blob/master/MC/run/PWGHF/embedding_benchmark.sh please? Probably some scripts need to be adjusted.

**Comment by gconesab** [comment]
Hi @sawenzel, I modified and did a quick test to your benchmark script, have a look. If ok we can merge.
G

**Comment by gconesab** [comment]
Hi @sandro, I see there is a conflict but I have no idea, I think I did rebase before modifying. Do you understand what is wrong?

**Comment by gconesab** [comment]
> /cc @sawenzel

ups, sorry!

**Comment by sawenzel** [comment]
@gconesab : I needed to update your PR since I did some mods at the same time. You should be able to squash-merge without a problem.

**Comment by gconesab** [comment]
> @gconesab : I needed to update your PR since I did some mods at the same time. You should be able to squash-merge without a problem.

It does not allow me unless I resolve the conflict.

**Comment by gconesab** [comment]
@sawenzel, can you check I did not do something wrong?

**Pull request merged**
