### PR TITLE
Add syntax checkers for Bash and Python

### PR DESCRIPTION
**Pull request by TimoWilken**

### CODE REVIEW

**Comment by TimoWilken** [comment]
Hi @benedikt-voelkel! I've added some basic checks for Bash and Python scripts -- one with `bash -n`, one with shellcheck (only showing the errors, no warnings or hints) and one with pylint (only errors as well).

These checkers find some existing problems -- those should probably be fixed before this is merged!

Also, let me know if you don't like any of the checkers, then I can improve or remove it.

I could also enable warning and/or hint messages, but there are quite a lot of them. These won't fail the check but will be shown in the "Files" tab of a PR.

**Comment by benedikt-voelkel** [comment]
Amazing, thanks a lot!
I will take a look in a bit.

**Comment by TimoWilken** [comment]
Rebased on master to get fixes from https://github.com/AliceO2Group/O2DPG/pull/1476. The remaining pylint issue may be spurious, I'll have a look in a bit. The shellcheck ones look genuine.

**Comment by TimoWilken** [comment]
Rebased; CI is all green now!

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
