### PR TITLE
Revert "Avoid complete randomness by default"

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
Reverts AliceO2Group/O2DPG#351

The seeds don't work and the simulation crashed with 
```bash
PYTHIA Error: variable recognized, but its value not meaningful:
   Random:seed = 6025226150559117445
  ```

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @davidrohr @shahor02 could you merge this?

**Comment by benedikt-voelkel** [comment]
Thanks for the quick action!
Some numbers seem to be too large probably or invalid for some other reason. I will have a look.

**Comment by chiarazampolli** [comment]
Maybe we could use the time in ms?

**Comment by chiarazampolli** [comment]
Or truncate this.

**Comment by benedikt-voelkel** [comment]
Yes, but Max' plan to make it semi-random, namely every simulation different but each single one reproducible. But actually the seed would be hard-coded in the `workflow.json`, so if the seed is fixed once, we can always re-use the workflow.
So we could use ms or anything else actually, what do you think @mpuccio @chiarazampolli ?

**Comment by chiarazampolli** [comment]
What matters is to keep track of it, 0 would have not allowed it but otherwise, whatever we do, we can print it.

**Comment by benedikt-voelkel** [comment]
Sounds good!
No, indeed as long as we have the number, it should be fine, To me it would be important to have method that can cover different generators consistently. I will think about it

**Comment by mpuccio** [comment]
I think we should anyway avoid the time, because log files are not easily programmatically accessibile. By the way, with further investigations we saw with @fgrosa that we need to modify deeper to propagate the seed to simulation with custom Pythia8 configurations. So we will come up with a better solution that does not rely on time and that we test a bit more, sorry for causing the issue with the tests!

**Comment by benedikt-voelkel** [comment]
ok, then it sounds like you will take over the implementation?
Thanks for the investigation!

**Pull request merged**
