### PR TITLE
Implement MC code for OmegacToXiPi

### PR DESCRIPTION
**Pull request by ZFederica**
Implement MC code for Omegac0 -> Xi pi

### CODE REVIEW

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
Dear @ZFederica 
As you can see the CI failed for your PR. The reason is that there is no test for you generator (I attached the message from the log file at the end).

We are now moving towards more thorough testing of custom generators to make sure that they work as expected. That means: Each `<config>.ini` file for generators needs to have a test defined. The procedure is explained here: https://aliceo2group.github.io/simulation/docs/generators/generatorconfig.html#generator-tests

There are already a few examples, for instance:
* https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGDQ/ini/tests/GeneratorHF_JPsiToMuons_fwdy.C
* https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGEM/ini/tests/GeneratorHF_bbbarToDDbarToDielectrons.C

Would it be possible for you to implement such a test for your `GeneratorHFOmegaCToXiPiEmb.ini`?
According to the examples given above and according to the documentation, what you would need is a macro like

```cpp
int External()
{
    // your test
    // if failure
    return 1;
    
    // no failure and in case everything good
    return 0;
}
```

Let me know if you need any help of course.


Here is the error from the error log

```bash
Following INI files will be tested:
  - MC/config/PWGHF/ini/GeneratorHFOmegaCToXiPiEmb.ini
[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGHF/ini/tests/GeneratorHFOmegaCToXiPiEmb.C not defined for ini file /O2DPG/MC/config/PWGHF/ini/GeneratorHFOmegaCToXiPiEmb.ini[0m
[0;31mError found in log /sw/BUILD/520c18948295b0ab16556de2ef5448c5779d96d7/O2DPG-sim-tests/o2dpg-sim_tests/o2dpg_tests/generators/o2dpg-test-kine.log[0m
1:[0;31m[FATAL]: O2DPG_TEST Script /O2DPG/MC/config/PWGHF/ini/tests/GeneratorHFOmegaCToXiPiEmb.C not defined for ini file /O2DPG/MC/config/PWGHF/ini/GeneratorHFOmegaCToXiPiEmb.ini[0m
```

**Comment by benedikt-voelkel** [comment]
Hello @ZFederica 
there were some technical problems with your test (see below at the end).

It is also possible to run the test locally, where you develop your code. I will send you some instructions via email.


```bash
-Processing External.C...
4-In file included from input_line_8:1:
5-/sw/BUILD/74236385403708dc8b7a90a771f5cc33811998d7/O2DPG-sim-tests/o2dpg-sim_tests/o2dpg_tests/generators/1_GeneratorHFOmegaCToXiPiEmb.ini_External_dir/External.C:64:30: error: declaration of variable 'cascade' with deduced type 'auto' requires an initializer
6-                        auto cascade;
7-                             ^
8-/sw/BUILD/74236385403708dc8b7a90a771f5cc33811998d7/O2DPG-sim-tests/o2dpg-sim_tests/o2dpg_tests/generators/1_GeneratorHFOmegaCToXiPiEmb.ini_External_dir/External.C:75:38: error: declaration of variable 'lambda' with deduced type 'auto' requires an initializer
9-                                auto lambda;
10-                                     ^
11-
12: *** Break *** segmentation violation
```

**Comment by benedikt-voelkel** [comment]
@ZFederica that looks good!
Do you have anything to add after the added implementations since your review @gconesab ? Otherwise, fell free to merge

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by gconesab** [comment]
I trust you, merging.

**Pull request merged**
