### PR TITLE
protection against corrupt O2DPG repository during topology generation

### PR DESCRIPTION
**Pull request by ehellbar**
I tested this locally both from scratch and with a corrupt repository from one of the topology generations today.

### CODE REVIEW

**Comment by ehellbar** [comment]
@davidrohr I updated the commit as we discussed
1) reset to HEAD from the start
2) clean untracked files

**Review by davidrohr — APPROVED** [review]
Thanks, looks good!
Have you tested it on the corrupted repository that you have saved?

**Comment by ehellbar** [comment]
Yes, it works as expected

**Comment by davidrohr** [comment]
great, then let's get it merged, and let's ask RC to deploy with the next SW update, since we had 2 such failures already.

**Pull request merged**
