### PR TITLE
[WF CI] Test also QC and AnalysisQC

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@sawenzel What do you think?
Should make it more reliable.

**Comment by benedikt-voelkel** [comment]
@TimoWilken 
Could we rerun the test here? Sandro put a fix for the known problem in O2.

**Comment by benedikt-voelkel** [comment]
Locally it's fine. It seems it did this one here with an older O2 where the problem persisted although fixed by https://github.com/AliceO2Group/AliceO2/pull/12457

If @sawenzel agrees, we can take this one in to be more sensitive to crucial changes

**Comment by chiarazampolli** [comment]
Label async-2023-pp-apass4 added to make the needed PR (https://github.com/AliceO2Group/O2DPG/pull/1686) apply

**Comment by chiarazampolli** [comment]
Tag for async-2023-pp-apass4 created, removing label.

**Pull request merged**
