### PR TITLE
MCH: get the onlyAtEndOfStream option be driven by an AliECS env var …

### PR DESCRIPTION
**Pull request by aphecetche**
…(MCH_END_OF_STREAM_ONLY)

This is to workaround the fact that the end-of-stream seems to be broken again.

### CODE REVIEW

**Comment by ktf** [comment]
Do you have a printout in readout-proxy for the end of stream being received?

**Comment by aphecetche** [comment]
something like this you mean ? 

(from `ssh epnlog@epn034 cat /tmp/wn_dds/7568f8b8-ff4a-444b-86e5-69d894671a58/wn_online_epn034-ib.internal/readout-proxy_reco2_2022-03-30-10-12-18_16894768857233317650_out.log`) 

```
[10:19:00][ERROR] device state change is requested, dropping 121600 pending message(s)
on channel from_readout-proxy_to_mch-pedestal-decoder
ATTENTION: DATA IS LOST! Could not dispatch data to downstream consumer(s), check if
consumers have been terminated too early
[10:19:00][INFO] Processing timeslice:5503, tfCounter:5503, firstTFOrbit:0, action:0
[10:19:00][ERROR] device state change is requested, dropping 121600 pending message(s)
on channel from_readout-proxy_to_mch-pedestal-decoder
ATTENTION: DATA IS LOST! Could not dispatch data to downstream consumer(s), check if
consumers have been terminated too early
[10:19:00][INFO] Processing timeslice:5504, tfCounter:5504, firstTFOrbit:0, action:0
[10:19:00][ERROR] device state change is requested, dropping 121600 pending message(s)
on channel from_readout-proxy_to_mch-pedestal-decoder
ATTENTION: DATA IS LOST! Could not dispatch data to downstream consumer(s), check if
consumers have been terminated too early
[10:19:00][INFO] Processing timeslice:5505, tfCounter:5505, firstTFOrbit:0, action:0
[10:19:00][ERROR] device state change is requested, dropping 121600 pending message(s)
on channel from_readout-proxy_to_mch-pedestal-decoder
ATTENTION: DATA IS LOST! Could not dispatch data to downstream consumer(s), check if
consumers have been terminated too early
```

**Comment by chiarazampolli** [comment]
We tested the MID calib this morning, and it worked, @dstocco .

**Comment by ktf** [comment]
this actually looks like you have huge backpressure on the channels… Is the
channelconfig configured properly?

Ciao,
Giulio

**Comment by ktf** [comment]
No, it should say "Sending end of stream to"

Ciao,
Giulio

**Comment by aphecetche** [comment]
@ktf @chiarazampolli indeed the end-of-stream is not the culprit here. We were testing with (most of) our FLPs (while previously we used only a couple) and were not requesting enough EPNs (or have enough raw decoders). 

Increasing the number of EPNs (and the raw decoder multiplicity factor) did result in the calibration working as before. 

Sorry for the false alarm.

**Pull request merged**
