### PR TITLE
PWGHF: add config for Pb-Pb MCs without pt hard bins for signal

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Review by stefanopolitano — APPROVED** [review]
Hi @fgrosa! Thank you for the PR. I don't have any comments. Approved!

**Comment by alcaliva** [comment]
this PR is now included in the tag for the Pb-Pb apass4 that is being built. Label removed

**Comment by alcaliva** [comment]
ciao @fgrosa, this PR gave me conflicts in the creation of the tag for async-2022-pp-apass7. I started from the tag async-v1-01-02d. Do you perhaps have any clue why this didn't work?

**Comment by alcaliva** [comment]
it worked for pp apass4 2023

**Comment by chiarazampolli** [comment]
Ported to async-v1-01-02f.

**Pull request merged**
