### PR TITLE
Forbid AOD merging to fail

### PR DESCRIPTION
**Pull request by chiarazampolli**
@jgrosseo : I kept the same logic as before, but in principle, failing merging should make the process exit now.

### CODE REVIEW

**Comment by jgrosseo** [comment]
Sounds good. And you keep the merging.log as well now, right?

**Comment by chiarazampolli** [comment]
Hello @jgrosseo ,
Yes, but this is in the jdl, so I will put it in place once I have a tag with this merged, to not have too large jobs. 
Is the level 0 for verbosity ok? I did not check the executable...
Chiara

**Comment by jgrosseo** [comment]
I checked and I think you can use level 1, it should not print too much.

**Comment by chiarazampolli** [comment]
Hi @jgrosseo , 

Thanks for checking.
Done! Let me know if now I can merge.

Chiara

**Comment by jgrosseo** [comment]
For me it looks good! Thanks!

**Comment by chiarazampolli** [comment]
Great, thanks to you!

**Pull request merged**
