### PR TITLE
Add files to simulate bbtomuons without forcing semileptonic decay

### PR DESCRIPTION
**Pull request by motomioya**
Add files and scripts to simulate bb -> mumu with natural decays. This includes modifications to GeneratorBeautyToMu_EvtGenFwdY().

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Approving to steer CI.

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
Dear @motomioya 
I approved to steer the CIs.
Now there is **new** `ini` file introduced by your PR: MC/config/PWGDQ/ini/GeneratorHF_bbbarToDDbarToMuons_fwdy.ini
Since these might be used to configure generators in production, we ask for a test that has to be implemented in addition. These tests should be macros that would check that your generator did was is expected.

An example
* `ini` file: https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGDQ/ini/GeneratorHF_JPsiToMuons_fwdy.ini
* corresponding test: https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGDQ/ini/tests/GeneratorHF_JPsiToMuons_fwdy.C

Documentation: https://aliceo2group.github.io/simulation/docs/generators/generatorconfig.html#generator-tests

Please let me know if you have additional questions.

**Comment by motomioya** [comment]
Dear @benedikt-voelkel
Thank you for the comment. I added a new file to MC/config/PWGDQ/ini/tests/GeneratorHF_bbbarToDDbarToMuons_fwdy.C for the new ini file test. I checked that it works and the test is successful in my local environment.

**Comment by benedikt-voelkel** [comment]
Amazing, thanks a lot!
I triggered the CI test to run, let's see how it goes!

**Review by benedikt-voelkel — APPROVED** [review]

**Pull request merged**
