### PR TITLE
CPV, PHS: update qc-async json config according to QC review 2023

### PR DESCRIPTION
**Pull request by sevdokim**
Hi! These changes bring modification of qc async jsons for CPV and PHS which were discussed during qc review 2023 together with Barth and Piotr.

### CODE REVIEW

**Comment by sevdokim** [comment]
Hi! Seems that I cannot add a label. 
Can you please add label +async-label async-data?

**Comment by chiarazampolli** [comment]
Hello @sevdokim , 

I can, but can you check that you don't see them on the left, as in this screenshot?

Screenshot 2024-03-18 at 11 10 31

Cheers,

Chiara

**Comment by sevdokim** [comment]
hi @chiarazampolli 
I see labels panel on the right but am not able to choose anything. See pic:
image

**Comment by chiarazampolli** [comment]
This is weird... @benedikt-voelkel , any idea?
For now I added the label myself.

Thanks!

Chiara

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @sevdokim The thing is that not everyone has write privileges in this repo. The message should contain what to do in those cases in order to add labels anyway.
Please have a look at:
>
>To request your PR to be included in production software, please add the corresponding labels called "async-" to your PR. 
>Add the labels directly (if you have the permissions) or add a comment of the form (note that labels are separated by a ",")
>
```
+async-label <label1>, <label2>, !<label3> ...
```
In that way, everyone should be able to add labels.

Please let me know if there are any questions.

**Comment by sevdokim** [comment]
Hi @benedikt-voelkel 
thanks for pointing this out. I will read more carefully next time.

**Comment by benedikt-voelkel** [comment]
No worries @sevdokim 
This approach is slowly being rolled out so it is good to get some feedback from everyone!

**Comment by chiarazampolli** [comment]
Thanks @benedikt-voelkel. Maybe we could change the text, because saying "please add the corresponding labels..." hints that one can directly add them?

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
