### PR TITLE
porting of MID aQC workflow to MC

### PR DESCRIPTION
**Pull request by lmassacr**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Looks good to me.
Are there any other comments from you @JianLIUhep @chiarazampolli ?

@lmassacr should this be included in the next tag for productions? E.g. PbPb apass3?

**Comment by JianLIUhep** [comment]
It's fine with me as well. No further comments on my side.

**Comment by lmassacr** [comment]
Hi @benedikt-voelkel, 

It can be included in any tag that will be used for MC production starting from now. However there is no emergency as we don't have yet a realistic Muon detector description in simulations. 

I am working now on the porting of aQC for MCH as well.

Thanks,
Laure

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @lmassacr , @benedikt-voelkel ,

Does this need updated QC?

If so, we need to ask @Barthelemy . 

@benedikt-voelkel : why did you add async-2023-pp-apass1? We are now running apass3.

Chiara

**Comment by benedikt-voelkel** [comment]
@chiarazampolli sorry for the additional label. I will remove it. I thought at this point that we would use it for pp 2023 in general.

**Pull request merged**
