### PR TITLE
MFT: Adding json query for cluster dictionary

### PR DESCRIPTION
**Pull request by tomas-herman**
- Adding a query for the cluster dictionary in the json files in O2DPG

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @tomas-herman 
did you test it with the [reproducer](https://alice.its.cern.ch/jira/secure/attachment/58975/reproducer.sh) of @sawenzel ?

**Comment by tomas-herman** [comment]
Hi, 
no I did not. I need to rebuild my `O2sim` for that.

**Comment by sawenzel** [comment]
@tomas-herman : Building O2sim does not take much longer than building QC. It's basically just a meta-package.

**Comment by tomas-herman** [comment]
Ok, but I just came back from vacation and I need to rebuild both O2 and QC. I will rebuild over night and should be able to test tomorrow.

**Comment by chiarazampolli** [comment]
Hi @tomas-herman ,

maybe it is then safer to move it to WIP. 

Chiara

**Comment by tomas-herman** [comment]
I have managed to run the reproducer script and it seems the test runs ok. I will remove the WIP if you agree.

Here is the output from the terminal:
```
[O2sim/latest] ~/alice/test_O2DPG $> bash reproducer.sh
Namespace(run=301000, productionTag='alibi_O2DPG_pp_minbias_pilotbeam_0.2T', timestamp=-1, anchor_config='', ns='22', gen='pythia8', proc='inel', trigger='', ini='', confKey='Diamond.width[2]=6', interactionRate='2000', bcPatternFile='/home/tomas/alice/test_O2DPG/bcPattern_Single_3b_2_2_2.root', eCM='900', eA=-1, eB=-1, col='pp', field='+2', ptHatMin=0, ptHatMax=-1, weightPow=-1, embedding=False, embeddPattern='@0:e1', nb=20, genBkg='', procBkg='heavy_ion', iniBkg='${O2DPG_ROOT}/MC/config/common/ini/basic.ini', confKeyBkg='', colBkg='PbPb', e='TGeant4', tf='1', production_offset=0, j=8, mod='--skipModules ZDC', with_ZDC=False, seed='624', o='workflow.json', noIPC=None, upload_bkg_to=None, use_bkg_from=None, early_tf_cleanup=False, no_combine_smaller_digi=False, no_combine_dpl_devices=False, no_tpc_digitchunking=False, combine_tpc_clusterization=False, first_orbit=0, run_anchored=False, include_qc=True, include_local_qc=False, include_analysis=True, mft_reco_full=False, mft_assessment_full=False, fwdmatching_assessment_full=False, fwdmatching_save_trainingdata=False)
** Using generic config **
Using initialisation seed:  624
Timeframe 1 seed:  130145275
=== There are 0 warnings ===
=== There are 0 errors ===
===> The workflow looks sane
Workflow saved at workflow.json
Enter PEM pass phrase:
Enter PEM pass phrase:
jobID: 1/1 >>> Start
jobID: 1/1 >>> STATUS OK >>> SPEED 3.16 KiB/s
Succesful jobs (1st try): 1/1
Stop on failure  True
setting up ROOT system
Launching task: o2-grp-simgrp-tool createGRPs --run 301000 --publishto ${ALICEO2_CCDB_LOCALCACHE:-.ccdb} -o grp --hbfpertf 256 --field +2 --readoutDets all --print --bcPatternFile /home/tomas/alice/test_O2DPG/bcPattern_Single_3b_2_2_2.root &> grpcreate.log &
Launching task: [ -f matbud.root ] || ${O2_ROOT}/bin/o2-ccdb-downloadccdbfile --host http://alice-ccdb.cern.ch/ -p GLO/Param/MatLUT -o matbud.root --no-preserve-path --timestamp 1546730800000 &> matbuddownloader.log &
Launching task: ${O2DPG_ROOT}/MC/config/common/pythia8/utils/mkpy8cfg.py --output=pythia8.cfg --seed=130145275 --idA=2212 --idB=2212 --eCM=900.0 --eA=-1.0 --eB=-1.0 --process=inel --ptHatMin=0.0 --ptHatMax=-1.0 &> gensgnconf_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim -e TGeant4 --skipModules ZDC -n 22 --seed 130145275 --field +2 -j 8 -g pythia8 --configKeyValues "GeneratorPythia8.config=pythia8.cfg;Diamond.width[2]=6" -o sgn_1 --timestamp 1546730800000 --run 301000 &> sgnsim_1.log &
Launching task: ln -nsf sgn_1_grp.root o2sim_grp.root ; ln -nsf sgn_1_geometry.root o2sim_geometry.root; ln -nsf sgn_1_geometry-aligned.root o2sim_geometry-aligned.root &> linkGRP_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim-digitizer-workflow --only-context --interactionRate 2000 -b --run -n 22 --sims sgn_1 --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" --bcPatternFile "/home/tomas/alice/test_O2DPG/bcPattern_Single_3b_2_2_2.root" &> digicontext_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim-digitizer-workflow -b --run -n 22 --sims sgn_1 --onlyDet TPC --interactionRate 2000 --tpc-lanes 8 --incontext collisioncontext.root --disable-write-ini --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" --tpc-chunked-writer &> tpcdigi_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim-digitizer-workflow -b --run -n 22 --sims sgn_1 --interactionRate 2000 --incontext collisioncontext.root --disable-write-ini --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" --onlyDet ITS,TOF,FDD,MCH,MID,MFT,HMP,EMC,PHS,CPV --ccdb-tof-sa --combine-devices  &> restdigi_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim-digitizer-workflow -b --run -n 22 --sims sgn_1 --onlyDet FT0,FV0,CTP --interactionRate 2000 --incontext collisioncontext.root --disable-write-ini --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" --combine-devices &> ft0fv0ctp_digi_1.log &
Launching task: ${O2_ROOT}/bin/o2-sim-digitizer-workflow -b --run -n 22 --sims sgn_1 --onlyDet TRD --interactionRate 2000 --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;TRDSimParams.digithreads=8" --incontext collisioncontext.root --disable-write-ini &> trddigi_1.log &
Launching task: ${O2_ROOT}/bin/o2-ft0-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> ft0reco_1.log &
Launching task: ${O2_ROOT}/bin/o2-fv0-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> fv0reco_1.log &
Launching task: ${O2_ROOT}/bin/o2-tpc-chunkeddigit-merger --tpc-sectors 0-17 --tpc-lanes 8 | ${O2_ROOT}/bin/o2-tpc-reco-workflow -b --run --shm-segment-size ${SHMSIZE:-50000000000} --input-type digitizer --output-type clusters,send-clusters-per-sector --outfile tpc-native-clusters-part0.root --tpc-sectors 0-17 --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;GPU_proc.ompThreads=4" &> tpcclusterpart0_1.log &
Launching task: ${O2_ROOT}/bin/o2-its-reco-workflow --trackerCA --tracking-mode async -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;ITSVertexerParam.phiCut=0.5;ITSVertexerParam.clusterContributorsCut=3;ITSVertexerParam.tanLambdaCut=0.2;NameConf.mDirMatLUT=.." &> itsreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-mft-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;MFTAlpideParam.roFrameLengthInBC=198" &> mftreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-mch-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> mchreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-tpc-chunkeddigit-merger --tpc-sectors 18-35 --tpc-lanes 8 | ${O2_ROOT}/bin/o2-tpc-reco-workflow -b --run --shm-segment-size ${SHMSIZE:-50000000000} --input-type digitizer --output-type clusters,send-clusters-per-sector --outfile tpc-native-clusters-part1.root --tpc-sectors 18-35 --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;GPU_proc.ompThreads=4" &> tpcclusterpart1_1.log &
Launching task: ${O2_ROOT}/bin/o2-mid-digits-reader-workflow | ${O2_ROOT}/bin/o2-mid-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> midreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-fdd-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> fddreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-emcal-reco-workflow --input-type digits --output-type cells --infile emcaldigits.root -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> emcalreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-phos-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> phsreco_1.log &
Launching task: ${O2_ROOT}/bin/o2-cpv-reco-workflow -b --run --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000" &> cpvreco_1.log &
/home/tomas/alice/sw/ubuntu2004_x86-64/O2/dev-local5/share/scripts/jobutils2.sh: line 101: kill: (141301) - No such process
Launching task: ${O2_ROOT}/bin/o2-muon-tracks-matcher-workflow -b --run  &> mchmidMatch_1.log &
Launching task: ${O2_ROOT}/bin/o2-globalfwd-matcher-workflow --configKeyValues "HBFUtils.orbitFirstSampled=0;HBFUtils.nHBFPerTF=256;HBFUtils.orbitFirst=0;HBFUtils.runNumber=301000;HBFUtils.startTime=1546730800000;FwdMatching.useMIDMatch=true" -b --run  &> mftmchMatch_1.log &
Launching task: ${O2_ROOT}/bin/o2-commonutils-treemergertool -i tpc-native-clusters-part*.root -o tpc-native-clusters.root -t tpcrec &> tpcclustermerge_1.log &

**** Pipeline done success (global_runtime : 404.629s) *****

Stop on failure  True
setting up ROOT system
Launching task: o2-trd-trap-sim | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/trd-digits-task.json --local-batch ../QC/trdDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> trdDigitsQC_local1.log &
Launching task: o2-qc-mft-digits-root-file-reader --mft-digit-infile=mftdigits.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-0.json --local-batch ../QC/mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftDigitsQC0_local1.log &
Launching task: ${O2_ROOT}/bin/o2-tof-reco-workflow --input-type digits --output-type none | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/tofdigits.json --local-batch ../QC/tofDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> tofDigitsQC_local1.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/tofdigits.json --remote-batch tofDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> tofDigitsQC_finalize.log &
Launching task: o2-global-track-cluster-reader --track-types "ITS" --cluster-types "ITS" | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/its-mc-tracks-qc.json --local-batch ../QC/ITSTrackSimTask.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> ITSTrackSimTask_local1.log &
Launching task: o2-global-track-cluster-reader --track-types none --cluster-types MFT | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-cluster.json --local-batch ../QC/mftClustersQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftClustersQC_local1.log &
Launching task: o2-emcal-cell-reader-workflow --infile emccells.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/emc-cell-task.json --local-batch ../QC/emcCellQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> emcCellQC_local1.log &
Launching task: o2-global-track-cluster-reader --track-types MFT --cluster-types MFT | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-async.json --local-batch ../QC/mftAsyncQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftAsyncQC_local1.log &
Launching task: o2-qc-mft-digits-root-file-reader --mft-digit-infile=mftdigits.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-1.json --local-batch ../QC/mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftDigitsQC1_local1.log &
/home/tomas/alice/sw/ubuntu2004_x86-64/O2/dev-local5/share/scripts/jobutils2.sh: line 101: kill: (142913) - No such process
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/tof-trending-hits.json --override-values "qc.config.Activity.number=0;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> tofTrendingHits.log &
Launching task: o2-qc-mft-digits-root-file-reader --mft-digit-infile=mftdigits.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-2.json --local-batch ../QC/mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftDigitsQC2_local1.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/trd-digits-task.json --remote-batch trdDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> trdDigitsQC_finalize.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/its-mc-tracks-qc.json --remote-batch ITSTrackSimTask.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> ITSTrackSimTask_finalize.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/emc-cell-task.json --remote-batch emcCellQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> emcCellQC_finalize.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-async.json --remote-batch mftAsyncQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> mftAsyncQC_finalize.log &
Launching task: o2-qc-mft-digits-root-file-reader --mft-digit-infile=mftdigits.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-3.json --local-batch ../QC/mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftDigitsQC3_local1.log &
Launching task: o2-ft0-recpoints-reader-workflow --infile o2reco_ft0.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/ft0-reconstruction-config.json --local-batch ../QC/RecPointsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> RecPointsQC_local1.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-cluster.json --remote-batch mftClustersQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> mftClustersQC_finalize.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/ft0-reconstruction-config.json --remote-batch RecPointsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> RecPointsQC_finalize.log &
Launching task: o2-qc-mft-digits-root-file-reader --mft-digit-infile=mftdigits.root | o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-4.json --local-batch ../QC/mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T;qc.config.Activity.start=1546730800000" -b --run  &> mftDigitsQC4_local1.log &
Launching task: o2-qc --config json://${O2DPG_ROOT}/MC/config/QC/json/qc-mft-digit-0.json --remote-batch mftDigitsQC.root --override-values "qc.config.Activity.number=301000;qc.config.Activity.periodName=alibi_O2DPG_pp_minbias_pilotbeam_0.2T" -b --run --driver-client-backend ws://  &> mftDigitsQC_finalize.log &

**** Pipeline done success (global_runtime : 111.586s) *****

[O2sim/latest] ~/alice/test_O2DPG $> 
```

**Comment by shahor02** [comment]
Thanks for testing, merging

**Review by shahor02 — APPROVED** [review]

**Comment by shahor02** [comment]
After confirming merge request it keeps asking the same. I guess git problem, will retry tomorrow

**Pull request merged**
