### PR TITLE
Use perVertexProcessing in Pb-Pb for ITS tracking

### PR DESCRIPTION
**Pull request by mpuccio**
This will only work for tags containing the changes of AliceO2Group/AliceO2#12498

### CODE REVIEW

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Error does not seem related to this PR, @mpuccio , can you confirm? Then I will merge.

**Comment by mconcas** [comment]
> Error does not seem related to this PR, @mpuccio , can you confirm? Then I will merge.

Hi, in CI logs it looks ITS did not find any seeding vertex and no tracks as well. Probably the error is not related to this pr by itself, but I'll investigate why it broke.

**Comment by chiarazampolli** [comment]
Thanks @mconcas !
What I saw was:

```
60263:ctf-writer]: [12:34:30][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
[60192:calib-emcalchannel-time]: [12:34:30][INFO] Saved data of the last slot to ./emc_calib/emc-time-calib.root
[60192:calib-emcalchannel-time]: [12:34:30][INFO] Sending end-of-stream message to channel from_calib-emcalchannel-time_to_mft-tracker
[60192:calib-emcalchannel-time]: [12:34:30][INFO] Sending end-of-stream message to channel from_calib-emcalchannel-time_to_tof-diagnostic-calibration
--
[60242:tpc-calibrator-gainmap-tracks]:     /lib64/libc.so.6:     ?? ??:0
[60242:tpc-calibrator-gainmap-tracks]:     o2-tpc-calibrator-gainmap-tracks() [0x420e0f]:     _start at ??:?
[60242:tpc-calibrator-gainmap-tracks]: Backtrace complete.
[ERROR] Workflow crashed - PID 60242 (tpc-calibrator-gainmap-tracks) did not exit correctly however it's not clear why. Exit code forced to 128.
[INFO] QUIT_REQUESTED
```

so I thought it was not ITS.

**Comment by shahor02** [comment]
Hi,
```
60263:ctf-writer]: [12:34:30][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
```
is irrelevant since the workflow has only 1 TF. But the fact that the ITS tracker did not find any seeding vertex is not normal and since there are clusters, might be related to the PR
```
its-tracker]: [12:34:11][INFO] ITSTracker pulled 125409 clusters, 11 RO frames
[60185:its-tracker]: [12:34:11][INFO] ITSTracker RO: continuous=1
[60185:its-tracker]: [12:34:11][INFO] Loading ITS L2G matrices from TGeo
[60185:its-tracker]: [12:34:11][INFO]  - Vertexer initialisation completed in: 0.308554 ms
[60185:its-tracker]: [12:34:11][INFO]  - Vertexer tracklet finding completed in: 1.29833 ms
[60185:its-tracker]: [12:34:11][INFO]  - Vertexer adjacent tracklets validation completed in: 0.090471 ms
[60185:its-tracker]: [12:34:11][INFO]  - Vertexer vertex finding completed in: 0.00612 ms
[60185:its-tracker]: [12:34:11][INFO]  - Timeframe 0 vertexing completed in: 1.7034731 ms, using 1 thread(s).
[60185:its-tracker]: [12:34:11][INFO]  - rejected 11/11 ROFs: random/mult.sel:11 (seed 624), vtx.sel:0
[60185:its-tracker]: [12:34:11][INFO]  - Vertex seeding total elapsed time: 1.7034731 ms for 0 vertices found in 11 ROFs
[60185:its-tracker]: [12:34:11][INFO]  - Beam position computed for the TF: 0, 0
```

**Comment by mconcas** [comment]
> Hi,
> 
> ```
> 60263:ctf-writer]: [12:34:30][ERROR] Some Lifetime::Timeframe data got dropped starting at 1
> ```
> 
> is irrelevant since the workflow has only 1 TF. But the fact that the ITS tracker did not find any seeding vertex is not normal and since there are clusters, might be related to the PR
> 
> ```
> its-tracker]: [12:34:11][INFO] ITSTracker pulled 125409 clusters, 11 RO frames
> [60185:its-tracker]: [12:34:11][INFO] ITSTracker RO: continuous=1
> [60185:its-tracker]: [12:34:11][INFO] Loading ITS L2G matrices from TGeo
> [60185:its-tracker]: [12:34:11][INFO]  - Vertexer initialisation completed in: 0.308554 ms
> [60185:its-tracker]: [12:34:11][INFO]  - Vertexer tracklet finding completed in: 1.29833 ms
> [60185:its-tracker]: [12:34:11][INFO]  - Vertexer adjacent tracklets validation completed in: 0.090471 ms
> [60185:its-tracker]: [12:34:11][INFO]  - Vertexer vertex finding completed in: 0.00612 ms
> [60185:its-tracker]: [12:34:11][INFO]  - Timeframe 0 vertexing completed in: 1.7034731 ms, using 1 thread(s).
> [60185:its-tracker]: [12:34:11][INFO]  - rejected 11/11 ROFs: random/mult.sel:11 (seed 624), vtx.sel:0
> [60185:its-tracker]: [12:34:11][INFO]  - Vertex seeding total elapsed time: 1.7034731 ms for 0 vertices found in 11 ROFs
> [60185:its-tracker]: [12:34:11][INFO]  - Beam position computed for the TF: 0, 0
> ```
Hi,

using (TL:DR; pulled every repo and o2dpg to this pr): 
`O2DPG@4252f5a16fbf3df59f0149808bef081fe944a6b3`,
`O2@d4eb41da0fa14defabcaeecb57d9c37d67a8e337`,
`alidist@59497dc2efe00503f428f48815d16399a4b2bd88`

I don't  have empty ITS reco and FST runs with no issues.

I ran:
```bash
#! /usr/bin/bash -xe

export JOBUTILS_PRINT_ON_ERROR=1
export JOBUTILS_JOB_TIMEOUT=1800
export PRINT_WORKFLOW=1
export NHBPERTF=128
export SHMSIZE=8000000000
export NJOBS=32
WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO
FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR
QC_REDIRECT_MERGER_TO_LOCALHOST=1
pwd
GEN_TOPO_WORKDIR=/sw/BUILD/68569ed3564ee0c409d2cd67bd76bd9f2f45d900/O2-full-system-test/full-system-test-sim
ALICE_O2SIM_DUMPLOG=1
NEvents=5
NEventsQED=100
O2SIMSEED=12345
${O2_ROOT}/prodtests/full_system_test.sh
```

and got:
```bash
[438310:its-tracker]: [15:21:12][INFO] ITSTracker pulled 110484 clusters, 11 RO frames
[438310:its-tracker]: [15:21:12][INFO] ITSTracker RO: continuous=1
[438310:its-tracker]: [15:21:12][INFO] Loading ITS L2G matrices from TGeo
[438310:its-tracker]: [15:21:12][INFO]  - Vertexer initialisation completed in: 0.088467 ms
[438310:its-tracker]: [15:21:12][INFO]  - Vertexer tracklet finding completed in: 0.55077 ms
[438310:its-tracker]: [15:21:12][INFO]  - Vertexer adjacent tracklets validation completed in: 0.059091 ms
[438310:its-tracker]: [15:21:12][INFO]  - Vertexer vertex finding completed in: 0.01106 ms
[438310:its-tracker]: [15:21:12][INFO]  - Timeframe 0 vertexing completed in: 0.709388 ms, using 1 thread(s).
[438310:its-tracker]: [15:21:12][INFO]  - rejected 10/11 ROFs: random/mult.sel:10 (seed 624), vtx.sel:0
[438310:its-tracker]: [15:21:12][INFO]  - Vertex seeding total elapsed time: 0.709388 ms for 1 vertices found in 11 ROFs
[438310:its-tracker]: [15:21:12][INFO]  - Beam position computed for the TF: 0.009329085, -0.006866491
[438310:its-tracker]: [15:21:12][INFO] ITS Tracking iteration 0 summary:
[438310:its-tracker]: [15:21:12][INFO]  - Timeframe initialisation completed in: 0.572571 ms
[438310:its-tracker]: [15:21:12][INFO] 	- Tracklet finding: 781 tracklets in 0.37 ms
[438310:its-tracker]: [15:21:12][INFO] 	- Cell finding: 569 cells found in 0.19 ms
[438310:its-tracker]: [15:21:12][INFO] 	- Neighbours finding: 408 neighbours found in 0.08 ms
[438310:its-tracker]: [15:21:12][INFO] 	- Track finding: 101 tracks found in 2.79 ms
[438310:its-tracker]: [15:21:12][INFO]  - Extending tracks completed in: 8e-05 ms
[438310:its-tracker]: [15:21:12][INFO]  - Short primaries finding completed in: 0.001082 ms
[438310:its-tracker]: [15:21:12][INFO]  - Timeframe 0 processing completed in: 4.01206ms using 1 threads.
[438310:its-tracker]: [15:21:12][INFO] ITSTracker pushed 101 tracks and 1 vertices
```

**Comment by chiarazampolli** [comment]
As discussed in person, this might be an effect of the prescaling that is applied in online and in the FSI when it dos sync reco for PbPb. Merging.

**Pull request merged**
