### PR TITLE
Update async_pass.sh

### PR DESCRIPTION
**Pull request by catalinristea**
Iterate a single input file for this special production.

### CODE REVIEW

**Comment by catalinristea** [comment]
Ciao @chiarazampolli,

In case we're decided now to go over a single input file per job, maybe this PR could help.
Otherwise, please disregard.
Thanks!

Yours,
Catalin.

**Comment by chiarazampolli** [comment]
Hi @catalinristea , 

I would actually prefer to have more CTF files in the job, to increase the statistics. 20 files, as you are using for 22o if I am not wrong, will be good. 

Cheers,

Chiara

**Comment by catalinristea** [comment]
Ciao @chiarazampolli,

I did the change we have discussed in the meeting.
Please review and merge it you find this appropriate.
Thanks!

Yours,
Catalin.

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Thanks @catalinristea !

**Pull request merged**
