### PR TITLE
To make it possible to run without the nodownload

### PR DESCRIPTION
**Pull request by chiarazampolli**
@catalinristea , please, let me know in case something is missing. I thought this was done already, but I was wrong.

### CODE REVIEW

**Comment by catalinristea** [comment]
Hi Chiara,

It looks good to me.

In case you want to stay with "turl" field, this will do it,
sed -rn 's/.*turl="([^"]*)".*/\1/p' wn.xml | awk -F "/" '{print $NF}' > list.list

Thanks,
Catalin.

**Comment by chiarazampolli** [comment]
Hello @catalinristea , 

Your line does not work for me, what could work is this:
```
sed -rn 's/.*turl="([^"]*)".*/\1/p' CTFs_10p.xml | awk -F "/" '{print $NF}'
```
Can you check? I have no preference, we can use any that works.
Chiara

**Comment by catalinristea** [comment]
Ciao Chiara,

Yes, it was the italics formatting of the web page which caught my asterisks.  Sorry about it, your line is perfectly fine.
Thanks!

Yours, Catalin.

**Comment by chiarazampolli** [comment]
Ah ok!
Since in the end it does not change, let's merge this one as it is - I assume you don't have a strong preference.
Chiara

**Comment by chiarazampolli** [comment]
Merging, failed tests are not related (e.g. missing token).

**Comment by alcaliva** [comment]
Adding labels "async-2024-pp-apass1" and "async-2024-pp-cpass0" in order to apply the PR https://github.com/AliceO2Group/O2DPG/pull/1698

**Pull request merged**
