### PR TITLE
PWGJE: Fixing wrong config

### PR DESCRIPTION
**Pull request by nzardosh**

### CODE REVIEW

**Comment by nzardosh** [comment]
+async-label async-2023-pbpb-apass4 async-2022-pp-apass7

**Comment by nzardosh** [comment]
+async-label async-2023-pbpb-apass4, async-2022-pp-apass7

**Comment by chiarazampolli** [comment]
@sawenzel , is this now ok?

**Comment by sawenzel** [comment]
+async-label async-2023-pbpb-apass4, async-2022-pp-apass7

**Pull request merged**
