### PR TITLE
Add script for updating qc configuration and replace all MC qc jsons to alice-ccdb

### PR DESCRIPTION
**Pull request by JianLIUhep**
- Added a script for updating qc configuration, a template for MC embedded  
- Replaced all conditionDB url to `alice-ccdb.cern.ch` and formatted all json files

### CODE REVIEW

**Comment by JianLIUhep** [comment]
Hi @chiarazampolli, can you please have a look if it's fine for the MC production? Thank you.

**Comment by JianLIUhep** [comment]
Hi @chiarazampolli, to summarize this PR:
- added one script to replace all the configuration contents for MC QC json files.
- added the default ccdb url in the corresponding MC scripts so that the url can be overwritten when setting up the workflow. 

But I did not touch the files under config/analysis_testing/json for now.

Both were tested and did not see any problem locally. 

If you agree, we can merge it.

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @JianLIUhep , 
Thanks! 
@sawenzel , would this PR be tested in the CI?
Chiara

**Comment by benedikt-voelkel** [comment]
@chiarazampolli 
It is tested to a certain point:
This test should be run for sure: https://github.com/AliceO2Group/O2DPG/blob/master/MC/bin/tests/wf_test_pp.sh
It does - unfortunately - not include AnalysisQC or QC, but I can change that quickly so that we can kick off a new test here.
In general, it might make sense to have a minimal QC and AnalysisQC test

**Comment by benedikt-voelkel** [comment]
Now, we have more of an infrastructural issue:
```
Git command for package 'Clang' failed.
Command: git clone --bare https://github.com/llvm/llvm-project /build/nomad/alloc/9e49f2a2-57e9-8608-48e1-c36dedaccf0b/ci/local/o2dpg-sim-tests/sw/MIRROR/clang
In directory: .
Exit code: -15
```

@TimoWilken I would indeed propose that I extend the MC test first to do the QC and AnalysisQC steps. It will be fast, only a very few events, like 10 or so.
Then, could we restart the test? I can ping you then

**Comment by TimoWilken** [comment]
Sounds good to me @benedikt-voelkel! The test has already restarted automatically and is green now.

**Comment by benedikt-voelkel** [comment]
This should be tested again once https://github.com/AliceO2Group/O2DPG/pull/1384 is merged.
Then it should finally be good to go!

**Comment by benedikt-voelkel** [comment]
Hello @JianLIUhep 
Could you rebase/resolve the conflicts?
We know also have additional checks for QC in place which should be useful especially for this PR.
Thanks a lot!

**Comment by JianLIUhep** [comment]
Hello @benedikt-voelkel, done.

**Comment by benedikt-voelkel** [comment]
@chiarazampolli this was now tested and since it was rebased just an hour ago, it had https://github.com/AliceO2Group/O2DPG/pull/1384 included; hence running a short simulation WF and QC as well as AnalysisQC on top of that.
So it seems that technically, the PR looks good.

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel , 
Thanks! @JianLIUhep , now the PR has conflicts, could you fix them? We merged changes to json files, maybe this is the cause.
Chiara

**Comment by benedikt-voelkel** [comment]
The conflicts should be gone @chiarazampolli 
At least here, I don't see any conflicts anymore

**Pull request merged**
