### PR TITLE
Switch EvselQA to PbPb configuration

### PR DESCRIPTION
**Pull request by nburmaso**
Passing correct flags for EventSelectionQA for Pb-Pb runs

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hej @nburmaso 
I think, we should have configurations for PbPb and pp at the same time right? Because AnalysisQC should be runnable for both collision systems at any time.
That would require a bit of work in the AnalysisQC steering scripts which I could do.

**Comment by nburmaso** [comment]
Hi @benedikt-voelkel!

Of course it would be better to have two configurations. Should we wait for the changes in the steering scripts and then add two json files in a different PR?

**Comment by benedikt-voelkel** [comment]
It is currently under discussion in DPG. I will get back here with news, hopefully this afternoon.

**Comment by nburmaso** [comment]
Ok, thank you, Benedikt :)

**Comment by benedikt-voelkel** [comment]
Closing, accounted for by #1255

**Pull request closed without merging**
