### PR TITLE
[WFRunner] Estimate resources dynamically

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* introduce functionality to update resource estimates based on values
  which are collected during monitoring
  (the same that go into pipeline_metric_<pid>.log)

* disentangle resource management from WorkflowExecutor

* manage resources via ResourceManager object
  * memory and cpu
  * semaphores
  * number of parallel tasks to be launched
  * niceness

* main interfaces of ResourceManager
  * ok_to_submit
  * book
  * unbook
  * add_monitored_resources

* group corresponding tasks together to be able to update resource
  estimates for upcoming tasks

* TaskResources as container of a task's resource estimate
  holding
  * resource estimates (initial and new estimates)
  * references to Semaphore object (optional
  * reference to list of related tasks (optional)

* make sure, final niceness assigned to a launched process is the same
  that the TaskResources hold for that process

* enable functionality with --dynamic-resources

* add more comments to classes and functions

* update --cgroup option to require entire path
  --> handle both cgroups v1 and cgroups v2

### CODE REVIEW

**Comment by fgrosa** [comment]
@chiarazampolli @alcaliva @sawenzel I put the label for the 2023 apass4 since I think it was missing in the last tag created. In particular, the https://github.com/AliceO2Group/O2DPG/pull/1640 was added, but it doesn't work without this one. 
I tested locally cherry picking it in the 2023 apass4 tag (O2DPG::async-20240229.pp.2d) and it worked without conflicts.

**Comment by alcaliva** [comment]
Hi @fgrosa, I tried to include this commit and I get conflicts

**Comment by fgrosa** [comment]
Hi @alcaliva sorry I completely missed your reply! 
For me it worked, see screenshot below:
grafik
Maybe it can be discussed today in the WP12/13 meeting. Thanks!

**Comment by alcaliva** [comment]
Thanks @fgrosa, I think I was starting from the wrong tag. Now it worked.

**Pull request merged**
