### PR TITLE
Define DCSCCDBSERVER_PERS env.var for persistent DCS CCDB server URL

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@shahor02 could you label this in case it should be ported? @mpuccio just said in an email thread this is a fix that seems to be needed in production.

**Comment by mpuccio** [comment]
Hi @benedikt-voelkel, I was actually referring to #1629, that is necessary for the skimming, for which I am specifying manually the O2DPG tag on top of the O2PDPSuite one (as I need also another modification that is not present in the tag used for apass7). I am not sure if the modification in #1629 is necessary in production.

**Comment by benedikt-voelkel** [comment]
Right, thanks for the clarification!

**Comment by shahor02** [comment]
Hi, no, this is for online calibrations only.

**Pull request merged**
