### PR TITLE
[EMCAL-757] Use cell reader as data source for cell level QC

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Depending on https://github.com/AliceO2Group/AliceO2/pull/8105. The reader was outsourced to a dedicated workfflow in order to provide a data source. This is much simpler than using the EMCAL reco workflow just to provide the cells. Not urgent as the current version via the reco workflow works as well.

**Comment by mfasDa** [comment]
Adding WIP flag as the commit should be merged after the next nightly if O2 is tagged, including the fix referenced above.

**Comment by mfasDa** [comment]
@chiarazampolli The corresponding part in O2 has been merged on Monday, can this be merged now as well?

**Comment by mfasDa** [comment]
@chiarazampolli @shahor02 Would it be possible to merge this pull request?

**Comment by chiarazampolli** [comment]
Sorry @mfasDa , I overlooked this. 
thanks, @davidrohr !

chiara

**Pull request merged**
