### PR TITLE
PWGHF: implement gap triggered MC for OmegacToXiPi

### PR DESCRIPTION
**Pull request by ZFederica**
Implement code for gap triggered MC for OmegaC --> Xi pi

### CODE REVIEW

**Comment by ZFederica** [comment]
@fgrosa could you please have a look?

**Review by gconesab — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
@TimoWilken do you know why the sim check is not scheduled?

**Comment by TimoWilken** [comment]
Hi @benedikt-voelkel, it says "started" now. Probably something else was building when this PR was submitted, sorry it's a bit slow sometimes!

**Comment by fgrosa** [comment]
@ZFederica sorry for the late reply, but I was attending LHCP. This is good for me, but I thought that it would be better to use the already defined methods, just adding a couple of arguments to pass the pdg of the hadron to trigger on and the rapidity window of it. In this way, the same method can be used for any triggered hadron and we do not have to define a new method for each hadron. Let me know if you want to implement it, otherwise I will do it. Thanks!

**Pull request merged**
