### PR TITLE
Creating the tar from root files only if there is a JDL env var that …

### PR DESCRIPTION
**Pull request by chiarazampolli**
…tells to do so

@catalinristea

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @catalinristea , 

If this seems ok to you, I will merge it.

Chiara

**Comment by catalinristea** [comment]
Ciao Chiara,
Yes, this was what I had in mind for it. Thanks a lot!
Yours, Catalin.

**Comment by chiarazampolli** [comment]
Thanks @catalinristea , if we want it for older tags than the one that will be created end of November, we need to add the labels. What do you think?
Chiara

**Comment by catalinristea** [comment]
Ciao Chiara! Yes, please flag it for all the active tags. It seems quite important feature for grid usage, but we can take it at the time of builds needed also for other things. Thanks!

Yours, Catalin.

**Comment by chiarazampolli** [comment]
Done, thanks.

**Comment by chiarazampolli** [comment]
This is not really needed for cpass0, but it was in the tag.

**Pull request merged**
