### PR TITLE
Trigger version of enhanced heavy-flavour dielectron MC (no gap)

### PR DESCRIPTION
**Pull request by rbailhac**
Trigger version of enhanced heavy-flavour dielectron MC (still without gap)

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@gconesab @rbailhac Did you check that the MC simulation CI passed? It seems it was not yet run before the merge. Just to make sure :)

**Comment by gconesab** [comment]
> @gconesab @rbailhac Did you check that the MC simulation CI passed? It seems it was not yet run before the merge. Just to make sure :)

My fault, confused between AliDPG and O2DPG

**Comment by rbailhac** [comment]
I will need time to run myself the MC simulation CI like here unfortunately. It looks like also that it checked only the first time but then skipped it (although I had a fix). If you prefer you can revert the commit.

**Comment by benedikt-voelkel** [comment]
No, it's fine. If you could just run the test yourself at some point, that would be great. In case a fix is needed, just open another PR I would say.
No problem

**Pull request merged**
