### PR TITLE
[Anchor] Remove -k from QC run, return error code

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
Additionally, some minor clarifications and transparent changes.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @catalinristea 
This allows to let `anchorMC.sh` return with the QC error code in case QC failed.
By default, the runner has the `-k` option which makes it keep going as far as possible. But that also means that the return code will be 0 by default.

See changed tests in this PR for examples.

If you agree, I would merge it.

**Comment by chiarazampolli** [comment]
Ciao @benedikt-voelkel , 

I think we should stop if QC fails, yes. Is this the case in production? Because I would have it there too.

Chiara

**Comment by chiarazampolli** [comment]
I personally think that failing QC should make the process fail. QC should just work. @JianLIUhep , Elena (I don't find her github name), @noferini , what do you think?

If 3 is possible, then it is good, so that we find all that would fail :-)

**Comment by benedikt-voelkel** [comment]
If we want to go for something like option 3, I would like @sawenzel to comment because I don't want to simply change the return code logic of the workflow runner itself.
But that decision can be made independent of this PR.

Until then, I would remove the `-k` option as default.
That would mean that for now, QC would abort on the first error and the achnorMC. return code would be different from 0.

For that I would need to make slight adjustments to this PR

**Comment by JianLIUhep** [comment]
Hi all, I am also in favor of having the option 3, and agree with above the comment by Benedikt.  

I cannot find Elena, either. Shared this PR with her.

**Comment by benedikt-voelkel** [comment]
Done: `-k` removed, QC run will abort as soon as there is an issue.
Discussion on option 3 to be followed up.

**Comment by benedikt-voelkel** [comment]
In case of no objections, I would merge this @chiarazampolli

**Pull request merged**
