### PR TITLE
no 1D channel histogram filling; new task and checks naming conventio…

### PR DESCRIPTION
**Pull request by jotwinow**
…n; added checker

### CODE REVIEW

**Comment by jotwinow** [comment]
@knopers8 Could you have a look and approve it. I need to delete the previous PR due mistake. We should have much less memory occupied by this task.

**Comment by chiarazampolli** [comment]
Hello @knopers8 ,
Can we merge?
Chiara

**Comment by chiarazampolli** [comment]
Hello @knopers8 , 
Can you take a look and merge if ok?
Thanks!
Chiara

**Comment by jotwinow** [comment]
Hi @knopers8, 
I hope you can make it soon.
Best regards, 
JO

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Merging, we'll test it in the RelVal for apss3.

**Pull request merged**
