### PR TITLE
Add TPC as default source for the svertexer

### PR DESCRIPTION
**Pull request by fmazzasc**
The work presented in https://indico.cern.ch/event/1351889/contributions/5696031/attachments/2762206/4810535/291123.pdf has been merged, and TPC only tracks have been added by default to the reconstruction. This PR updates the reconstruction in the simulation as well. @ddobrigk @shahor02 @f3sch

### CODE REVIEW

**Review by sawenzel — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @sawenzel , @fmazzasc , 
Is this needed for MC anchored to PbPb 2023 apass1? As you know, we are cherry picking changes, as discussed in https://alice-dpg.docs.cern.ch/software/requests/2023pbpb_apass.html
Chiara

**Comment by ddobrigk** [comment]
Ciao! Sorry for jumping in. @fmazzasc super thanks for doing this! And @chiarazampolli yes we absolutely need to have this in the MC anchored or strangeness settings won't match. Thanks a lot!

**Comment by chiarazampolli** [comment]
This was not ported, and we are starting PbPb MC... So we need a new tag. 
Please, add it in the sw request gitlab page.
@catalinristea , @noferini , FYI.

**Comment by ddobrigk** [comment]
@chiarazampolli thanks and sorry for the trouble! Tagging @shahor02 and @f3sch for completeness (also since this impacts directly the use of the photon stuff in the MC), in case there's still something missing in addition.

**Pull request merged**
