### PR TITLE
MCH: add async qc

### PR DESCRIPTION
**Pull request by aphecetche**
This PR introduces the long overdue async part of the QC for MCH.

Note that I've moved the `add_QC_JSON` up in the `qc-workflow.sh` script in order to be able to use it in the async part to construct the MCH part from parts.

@aferrero2707 FYI

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
QC configs look OK, I can't judge for the script

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
Maybe you want to take a look at the script before we merge?
Chiara

**Comment by davidrohr** [comment]
Moving the code up is fine with me. What I am not fully sure is the change of the database host to localhost. Ccdb-test certainly does not make much sense, but why do we set it to localhost?

**Comment by aphecetche** [comment]
@davidrohr good catch. That's actually a remnant of my local tests, not intended. Not in front of a (real) computer right now, will change it later today.

**Comment by aphecetche** [comment]
@davidrohr I've reverted the unintended change to the ccdb in `QC_CONFIG_OVERRIDE` (and actually use add_QC_JSON in two more places for MCH, like I've been using in my latest tests)

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
Can this be merged now?
Chiara

**Pull request merged**
