### PR TITLE
ITS::tracking: stop fatalising job, drop TF instead

### PR DESCRIPTION
**Pull request by mconcas**
Change the default behaviour, provided https://github.com/AliceO2Group/AliceO2/pull/13791 is included.
We stop breaking the processing if too much memory is required, we cleanup and move to the next TF.
@shahor02 @chiarazampolli @alcaliva

### CODE REVIEW

**Comment by shahor02** [comment]
Thanks @mconcas.

For @chiarazampolli and @alcaliva : Matteo sees that the reconstruction with ITS per-ROF mode (instead of per-Vertex mode used in PbPb23 causing some inefficiencies) may crash due to the high memory if there are 2 central collisions in the same ROF.
This is a protection to skip the TF if the combinatorics grows too high.
We should use this option if we go to per-ROF ITS processing.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 
If this is only when Per-PV is not enabled, should we have an `if`?
Chiara

**Comment by mconcas** [comment]
> Hello @shahor02 , If this is only when Per-PV is not enabled, should we have an `if`? Chiara

This is regardless the per-PV, we see that there are anyways crashes even with the perPV, much less but still.
So I would treat thise as a default option for PbPb in general. Not to be backported, as it affects only the % of success and not directly the physics.

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Thanks, merged.

**Pull request merged**
